// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

// Package daemon — The daemon role on the framework — the listener of the
// contract, the jobs, the measure of sessions for the idle stop, and
// `statusline daemon status|stop`, which ask the instance's daemon through the
// contract. The instance lock, the private socket that only accepts its own
// user, the contract's operations, the loops, the heartbeat, the stop once no
// session asked for a minute or after an update, a bounded log.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package daemon

import (
	"context"
	"time"

	"github.com/kitsunium/sdk/framework/kit"
	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/sdk/pkg/v1/ipc"
	"github.com/kitsunium/statusline/collect/collector"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 3, 255), "NOT_IMPLEMENTED", "not implemented yet", "daemon: a hand-written body is still a skeleton")

// Service is daemon's framework service: what it declares, drawn and run.
var Service = kit.NewService("daemon", "The daemon role on the framework — the listener of the contract, the jobs, the measure of sessions for the idle stop, and `statusline daemon status|stop`, which ask the instance's daemon through the contract. The instance lock, the private socket that only accepts its own user, the contract's operations, the loops, the heartbeat, the stop once no session asked for a minute or after an update, a bounded log.")

var _ = Service.Listen("daemon", "daemon/v1", Serve, kit.SocketPer(kit.PerUID, kit.PerExecutable, kit.PerEnv("CLAUDE_CONFIG_DIR", "~/.claude")))

// Serve serves a connection of daemon (daemon/v1): its body is the hand-written serve.
func Serve(ctx context.Context, conn *ipc.Conn) error {
	return serve(ctx, conn)
}

var _ = Service.CLI("status", "says what the instance's daemon is doing", Status)

// Status runs "status": its body is the hand-written status.
func Status(ctx context.Context, args []string, std kit.Stdio) int {
	return status(ctx, args, std)
}

var _ = Service.CLI("stop", "stops the instance's daemon", Stop)

// Stop runs "stop": its body is the hand-written stop.
func Stop(ctx context.Context, args []string, std kit.Stdio) int {
	return stop(ctx, args, std)
}

var _ = Service.Every("tick", time.Second, Tick)

// Tick — The refresh, the eviction, the heartbeat.
func Tick(ctx context.Context) error {
	return tick(ctx)
}

var _ = Service.Every("update", time.Hour, Update)

// Update — The silent self-update (D11); the daemon stops after an install.
func Update(ctx context.Context) error {
	return update(ctx)
}

var _ = Service.Activity(Busy)

// Busy says whether daemon has work in progress, for the idle stop of the
// daemon that mounts it: its body is the hand-written busy.
func Busy(ctx context.Context) bool {
	return busy(ctx)
}

// wired is what the handlers' twins reach, set by the role that mounts
// the component (Wire).
var wired struct {
	collectSnapshot collector.CollectSnapshot
	latestNetwork   collector.LatestNetwork
	sessionCache    collector.SessionCacheV1
	updateStore     collector.UpdateStoreV1
	version         string
	refreshNetwork  collector.RefreshNetwork
	clock           collector.ClockV1
	checkUpdate     collector.CheckUpdate
}

// Wire gives the handlers what they use: the role that mounts daemon calls it
// before its App runs.
func Wire(collectSnapshot collector.CollectSnapshot, latestNetwork collector.LatestNetwork, sessionCache collector.SessionCacheV1, updateStore collector.UpdateStoreV1, version string, refreshNetwork collector.RefreshNetwork, clock collector.ClockV1, checkUpdate collector.CheckUpdate) {
	wired.collectSnapshot = collectSnapshot
	wired.latestNetwork = latestNetwork
	wired.sessionCache = sessionCache
	wired.updateStore = updateStore
	wired.version = version
	wired.refreshNetwork = refreshNetwork
	wired.clock = clock
	wired.checkUpdate = checkUpdate
}
