// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fd66b2b6a3694bc24ec48192c387084ddcee0ebf9262003e13519df5987eff47

// Package daemon — The daemon role's entry — `statusline daemon` serves;
// `statusline daemon status|stop` asks the instance's daemon through the
// contract and prints. The instance lock, the private socket that only accepts
// its own user, the contract's operations, the loops, the heartbeat, the stop
// once no session asked for a minute or after an update, a bounded log.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package daemon

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/ipc"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 3, 255), "NOT_IMPLEMENTED", "not implemented yet", "daemon: a hand-written body is still a skeleton")

// Listener is an adapter of the design.
type Listener struct {
	listener // its own state, hand-written
}

// NewListener builds Listener: its body is the hand-written newListener.
func NewListener(collectSnapshot collector.CollectSnapshot, latestNetwork collector.LatestNetwork, refreshNetwork collector.RefreshNetwork, checkUpdate collector.CheckUpdate, sessionCache collector.SessionCacheV1, updateStore collector.UpdateStoreV1, clock collector.ClockV1, version string) *Listener {
	return newListener(collectSnapshot, latestNetwork, refreshNetwork, checkUpdate, sessionCache, updateStore, clock, version)
}

// Run is collect/port/Command@v1's.
func (a *Listener) Run(ctx context.Context, args []string) error {
	return a.run(ctx, args)
}

var _ collector.CommandV1 = (*Listener)(nil)

// Snapshot is collect/port/Daemon@v1's.
func (a *Listener) Snapshot(ctx context.Context, key ipc.Key) (snapshot.Snapshot, error) {
	return a.snapshot(ctx, key)
}

// Status is collect/port/Daemon@v1's.
func (a *Listener) Status(ctx context.Context) (ipc.Status, error) {
	return a.status(ctx)
}

// Stop is collect/port/Daemon@v1's.
func (a *Listener) Stop(ctx context.Context) error {
	return a.stop(ctx)
}

var _ collector.DaemonV1 = (*Listener)(nil)
