// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package session — The host's stdin payload and what it says about the
// session.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package session

import (
	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/quota"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 2, 1, 255), "NOT_IMPLEMENTED", "not implemented yet", "session: a hand-written body is still a skeleton")

const (
	// EffortHigh is a constant of the design.
	EffortHigh string = "high"
	// EffortLow is a constant of the design.
	EffortLow string = "low"
	// EffortMax is a constant of the design.
	EffortMax string = "max"
	// EffortMedium is a constant of the design.
	EffortMedium string = "medium"
	// EffortXHigh is a constant of the design.
	EffortXHigh string = "xhigh"
)

// ModelInfo is a value object of the design.
type ModelInfo struct {
	Name    string
	Version string
}

// FullName is a method of the design.
func (m ModelInfo) FullName() string {
	return m.fullName()
}

// ShortName is a method of the design.
func (m ModelInfo) ShortName() string {
	return m.shortName()
}

// Payload — The JSON the host pipes on stdin. Every field the host sends is
// declared with its type, so that a mistyped field is refused as the legacy
// product refused it.
type Payload struct {
	Model         PayloadModel      `json:"model"`
	Workspace     PayloadWorkspace  `json:"workspace"`
	ContextWindow PayloadContext    `json:"context_window"`
	Cost          PayloadCost       `json:"cost"`
	RateLimits    PayloadRateLimits `json:"rate_limits"`
	Effort        PayloadEffort     `json:"effort"`
	Thinking      PayloadThinking   `json:"thinking"`
	OutputStyle   PayloadStyle      `json:"output_style"`
	SessionName   string            `json:"session_name"`
	Transcript    string            `json:"transcript_path"`
	SessionID     string            `json:"session_id"`
	Version       string            `json:"version"`
	FastMode      bool              `json:"fast_mode"`
	Exceeds200k   bool              `json:"exceeds_200k_tokens"`
}

// ContextWindowSize is a method of the design.
func (p *Payload) ContextWindowSize() int {
	return p.contextWindowSize()
}

// ModelInfo is a method of the design.
func (p *Payload) ModelInfo() ModelInfo {
	return p.modelInfo()
}

// Progress is a method of the design.
func (p *Payload) Progress() quota.Progress {
	return p.progress()
}

// StdinLimits is a method of the design.
func (p *Payload) StdinLimits() quota.Set {
	return p.stdinLimits()
}

// TotalTokens is a method of the design.
func (p *Payload) TotalTokens() int {
	return p.totalTokens()
}

// WorkingDir is a method of the design.
func (p *Payload) WorkingDir() string {
	return p.workingDir()
}

// PayloadContext is a value object of the design.
type PayloadContext struct {
	CurrentUsage        PayloadUsage `json:"current_usage"`
	TotalInputTokens    int          `json:"total_input_tokens"`
	TotalOutputTokens   int          `json:"total_output_tokens"`
	ContextWindowSize   int          `json:"context_window_size"`
	UsedPercentage      *float64     `json:"used_percentage"`
	RemainingPercentage *float64     `json:"remaining_percentage"`
}

// PayloadCost is a value object of the design.
type PayloadCost struct {
	TotalCostUSD       float64 `json:"total_cost_usd"`
	TotalDurationMs    int64   `json:"total_duration_ms"`
	TotalAPIDurationMs int64   `json:"total_api_duration_ms"`
	TotalLinesAdded    int     `json:"total_lines_added"`
	TotalLinesRemoved  int     `json:"total_lines_removed"`
}

// PayloadEffort is a value object of the design.
type PayloadEffort struct {
	Level string `json:"level"`
}

// PayloadModel is a value object of the design.
type PayloadModel struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

// PayloadRateLimit is a value object of the design.
type PayloadRateLimit struct {
	UsedPercentage *float64        `json:"used_percentage"`
	Utilization    *float64        `json:"utilization"`
	ResetsAt       quota.Timestamp `json:"resets_at"`
}

// Percent is a method of the design.
func (p *PayloadRateLimit) Percent() (int, bool) {
	return p.percent()
}

// PayloadRateLimits is a value object of the design.
type PayloadRateLimits struct {
	FiveHour *PayloadRateLimit `json:"five_hour"`
	SevenDay *PayloadRateLimit `json:"seven_day"`
}

// PayloadStyle is a value object of the design.
type PayloadStyle struct {
	Name string `json:"name"`
}

// PayloadThinking is a value object of the design.
type PayloadThinking struct {
	Enabled bool `json:"enabled"`
}

// PayloadUsage is a value object of the design.
type PayloadUsage struct {
	InputTokens              int `json:"input_tokens"`
	OutputTokens             int `json:"output_tokens"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int `json:"cache_read_input_tokens"`
}

// PayloadWorkspace is a value object of the design.
type PayloadWorkspace struct {
	CurrentDir string `json:"current_dir"`
	ProjectDir string `json:"project_dir"`
}

// EffortRank is a function of the design.
func EffortRank(level string) (int, bool) {
	return effortRank(level)
}

// EffortSteps is a function of the design.
func EffortSteps() int {
	return effortSteps()
}

// Parse never fails — invalid JSON is the zero Payload, a mistyped field
// leaves the fields decoded around it.
func Parse(data []byte) Payload {
	return parse(data)
}
