// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package session

import (
	"hash/fnv"
	"os"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// TestPropertyModelInfoFullNameStartsWithName holds render/ModelInfo.FullName by property StartsWithName.
func TestPropertyModelInfoFullNameStartsWithName(t *testing.T) {
	propertyModelInfoFullNameStartsWithName(t, designSeed("render/ModelInfo.FullName#StartsWithName"))
}

// TestPropertyModelInfoShortNamePrefixOfFull holds render/ModelInfo.ShortName by property PrefixOfFull.
func TestPropertyModelInfoShortNamePrefixOfFull(t *testing.T) {
	propertyModelInfoShortNamePrefixOfFull(t, designSeed("render/ModelInfo.ShortName#PrefixOfFull"))
}

// TestPropertyPayloadContextWindowSizePositive holds render/Payload.ContextWindowSize by property Positive.
func TestPropertyPayloadContextWindowSizePositive(t *testing.T) {
	propertyPayloadContextWindowSizePositive(t, designSeed("render/Payload.ContextWindowSize#Positive"))
}

// TestPropertyPayloadModelInfoDefaultName holds render/Payload.ModelInfo by property DefaultName.
func TestPropertyPayloadModelInfoDefaultName(t *testing.T) {
	propertyPayloadModelInfoDefaultName(t, designSeed("render/Payload.ModelInfo#DefaultName"))
}

// TestPropertyPayloadProgressBounded holds render/Payload.Progress by property Bounded.
func TestPropertyPayloadProgressBounded(t *testing.T) {
	propertyPayloadProgressBounded(t, designSeed("render/Payload.Progress#Bounded"))
}

// TestPropertyPayloadStdinLimitsContextAlways holds render/Payload.StdinLimits by property ContextAlways.
func TestPropertyPayloadStdinLimitsContextAlways(t *testing.T) {
	propertyPayloadStdinLimitsContextAlways(t, designSeed("render/Payload.StdinLimits#ContextAlways"))
}

// TestPropertyPayloadTotalTokensSum holds render/Payload.TotalTokens by property Sum.
func TestPropertyPayloadTotalTokensSum(t *testing.T) {
	propertyPayloadTotalTokensSum(t, designSeed("render/Payload.TotalTokens#Sum"))
}

// TestPropertyPayloadWorkingDirNeverEmpty holds render/Payload.WorkingDir by property NeverEmpty.
func TestPropertyPayloadWorkingDirNeverEmpty(t *testing.T) {
	propertyPayloadWorkingDirNeverEmpty(t, designSeed("render/Payload.WorkingDir#NeverEmpty"))
}

// TestPropertyPayloadRateLimitPercentPrefersUsed holds render/PayloadRateLimit.Percent by property PrefersUsed.
func TestPropertyPayloadRateLimitPercentPrefersUsed(t *testing.T) {
	propertyPayloadRateLimitPercentPrefersUsed(t, designSeed("render/PayloadRateLimit.Percent#PrefersUsed"))
}

// TestPropertyEffortRankScale holds render/function/EffortRank by property Scale.
func TestPropertyEffortRankScale(t *testing.T) {
	propertyEffortRankScale(t, designSeed("render/function/EffortRank#Scale"))
}

// TestPropertyEffortStepsMatchesScale holds render/function/EffortSteps by property MatchesScale.
func TestPropertyEffortStepsMatchesScale(t *testing.T) {
	propertyEffortStepsMatchesScale(t, designSeed("render/function/EffortSteps#MatchesScale"))
}

// TestPropertyParseTotal holds render/function/Parse by property Total.
func TestPropertyParseTotal(t *testing.T) {
	propertyParseTotal(t, designSeed("render/function/Parse#Total"))
}
