// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:2fe8d86cbae61dd09910f21ff1088719bef537ae1defa6374bdd41ff060206d8

package session

import (
	"flag"
	"hash/fnv"
	"os"
	"strconv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:2fe8d86cbae61dd09910f21ff1088719bef537ae1defa6374bdd41ff060206d8"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// useSeed logs a property's seed and hands it to pgregory.net/rapid, whose
// only public way in is its -rapid.seed flag: rapid.Check then draws the same
// values in every run of the same design — and in kit test -seed's.
func useSeed(t *testing.T, seed uint64) {
	t.Helper()
	t.Logf("property seed %d (go test -rapid.seed=%d replays it)", seed, seed)
	if f := flag.Lookup("rapid.seed"); f != nil {
		_ = f.Value.Set(strconv.FormatUint(seed, 10))
	}
}

// TestPropertyModelInfoFullNameStartsWithName holds render/ModelInfo.FullName by property StartsWithName.
func TestPropertyModelInfoFullNameStartsWithName(t *testing.T) {
	seed := designSeed("render/ModelInfo.FullName#StartsWithName")
	useSeed(t, seed)
	propertyModelInfoFullNameStartsWithName(t, seed)
}

// TestPropertyModelInfoShortNamePrefixOfFull holds render/ModelInfo.ShortName by property PrefixOfFull.
func TestPropertyModelInfoShortNamePrefixOfFull(t *testing.T) {
	seed := designSeed("render/ModelInfo.ShortName#PrefixOfFull")
	useSeed(t, seed)
	propertyModelInfoShortNamePrefixOfFull(t, seed)
}

// TestPropertyPayloadContextWindowSizePositive holds render/Payload.ContextWindowSize by property Positive.
func TestPropertyPayloadContextWindowSizePositive(t *testing.T) {
	seed := designSeed("render/Payload.ContextWindowSize#Positive")
	useSeed(t, seed)
	propertyPayloadContextWindowSizePositive(t, seed)
}

// TestPropertyPayloadModelInfoDefaultName holds render/Payload.ModelInfo by property DefaultName.
func TestPropertyPayloadModelInfoDefaultName(t *testing.T) {
	seed := designSeed("render/Payload.ModelInfo#DefaultName")
	useSeed(t, seed)
	propertyPayloadModelInfoDefaultName(t, seed)
}

// TestPropertyPayloadProgressBounded holds render/Payload.Progress by property Bounded.
func TestPropertyPayloadProgressBounded(t *testing.T) {
	seed := designSeed("render/Payload.Progress#Bounded")
	useSeed(t, seed)
	propertyPayloadProgressBounded(t, seed)
}

// TestPropertyPayloadStdinLimitsContextAlways holds render/Payload.StdinLimits by property ContextAlways.
func TestPropertyPayloadStdinLimitsContextAlways(t *testing.T) {
	seed := designSeed("render/Payload.StdinLimits#ContextAlways")
	useSeed(t, seed)
	propertyPayloadStdinLimitsContextAlways(t, seed)
}

// TestPropertyPayloadTotalTokensSum holds render/Payload.TotalTokens by property Sum.
func TestPropertyPayloadTotalTokensSum(t *testing.T) {
	seed := designSeed("render/Payload.TotalTokens#Sum")
	useSeed(t, seed)
	propertyPayloadTotalTokensSum(t, seed)
}

// TestPropertyPayloadWorkingDirNeverEmpty holds render/Payload.WorkingDir by property NeverEmpty.
func TestPropertyPayloadWorkingDirNeverEmpty(t *testing.T) {
	seed := designSeed("render/Payload.WorkingDir#NeverEmpty")
	useSeed(t, seed)
	propertyPayloadWorkingDirNeverEmpty(t, seed)
}

// TestPropertyPayloadRateLimitPercentPrefersUsed holds render/PayloadRateLimit.Percent by property PrefersUsed.
func TestPropertyPayloadRateLimitPercentPrefersUsed(t *testing.T) {
	seed := designSeed("render/PayloadRateLimit.Percent#PrefersUsed")
	useSeed(t, seed)
	propertyPayloadRateLimitPercentPrefersUsed(t, seed)
}

// TestPropertyEffortRankScale holds render/function/EffortRank by property Scale.
func TestPropertyEffortRankScale(t *testing.T) {
	seed := designSeed("render/function/EffortRank#Scale")
	useSeed(t, seed)
	propertyEffortRankScale(t, seed)
}

// TestPropertyEffortStepsMatchesScale holds render/function/EffortSteps by property MatchesScale.
func TestPropertyEffortStepsMatchesScale(t *testing.T) {
	seed := designSeed("render/function/EffortSteps#MatchesScale")
	useSeed(t, seed)
	propertyEffortStepsMatchesScale(t, seed)
}

// TestPropertyParseTotal holds render/function/Parse by property Total.
func TestPropertyParseTotal(t *testing.T) {
	seed := designSeed("render/function/Parse#Total")
	useSeed(t, seed)
	propertyParseTotal(t, seed)
}
