// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

// Package daemon — One per (UID, host configuration directory, executable),
// started by a client, stopped a minute after the last redraw.
package daemon

import (
	"context"

	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/collect/credentials"
	daemonc "github.com/kitsunium/statusline/collect/daemon"
	"github.com/kitsunium/statusline/collect/gitcli"
	"github.com/kitsunium/statusline/collect/mcpconfig"
	"github.com/kitsunium/statusline/collect/releases"
	"github.com/kitsunium/statusline/collect/sessioncache"
	"github.com/kitsunium/statusline/collect/sessions"
	"github.com/kitsunium/statusline/collect/statefile"
	"github.com/kitsunium/statusline/collect/statuspage"
	"github.com/kitsunium/statusline/collect/sysinfo"
	"github.com/kitsunium/statusline/collect/taskstore"
	"github.com/kitsunium/statusline/collect/transcripts"
	"github.com/kitsunium/statusline/collect/usageapi"
	"github.com/kitsunium/statusline/collect/wallclock"
)

// Build is what the binary's build says: its variables, set by -ldflags -X.
type Build struct {
	Version   string
	VendorKey string
}

// Run builds role daemon and runs collect/adapter/Listener.
func Run(ctx context.Context, args []string, build Build) error {
	clock := wallclock.NewClock()
	cache := sessioncache.NewCache()
	transcripts := transcripts.NewTranscripts()
	sessions := sessions.NewSessions()
	git := gitcli.NewGit()
	system := sysinfo.NewSystem()
	config := mcpconfig.NewConfig()
	tasks := taskstore.NewTasks()
	files := statefile.NewFiles()
	latestNetwork := collector.NewLatestNetwork(clock, files)
	collectSnapshot := collector.NewCollectSnapshot(clock, cache, transcripts, sessions, git, system, transcripts, config, tasks, latestNetwork, files)
	credentials := credentials.NewCredentials()
	usage := usageapi.NewUsage()
	statusPage := statuspage.NewStatusPage()
	refreshNetwork := collector.NewRefreshNetwork(clock, files, credentials, usage, statusPage)
	releases := releases.NewReleases(build.Version, build.VendorKey)
	checkUpdate := collector.NewCheckUpdate(clock, files, releases)
	listener := daemonc.NewListener(collectSnapshot, latestNetwork, refreshNetwork, checkUpdate, cache, files, clock, build.Version)
	return listener.Run(ctx, args)
}
