// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

// Package statefile — The instance's state files: network and update
// bookkeeping, and every key's last snapshot for a cold client.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package statefile

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/collect/state"
	"github.com/kitsunium/statusline/ipc"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 13, 255), "NOT_IMPLEMENTED", "not implemented yet", "statefile: a hand-written body is still a skeleton")

// Files is an adapter of the design.
type Files struct {
	files // its own state, hand-written
}

// NewFiles builds Files: its body is the hand-written newFiles.
func NewFiles() *Files {
	return newFiles()
}

// LoadNetwork is collect/port/NetworkStore@v1's.
func (a *Files) LoadNetwork(ctx context.Context) (state.Network, error) {
	return a.loadNetwork(ctx)
}

// SaveNetwork is collect/port/NetworkStore@v1's.
func (a *Files) SaveNetwork(ctx context.Context, n state.Network) error {
	return a.saveNetwork(ctx, n)
}

var _ collector.NetworkStoreV1 = (*Files)(nil)

// SaveSnapshot is collect/port/SnapshotCache@v1's.
func (a *Files) SaveSnapshot(ctx context.Context, key ipc.Key, snap snapshot.Snapshot) error {
	return a.saveSnapshot(ctx, key, snap)
}

var _ collector.SnapshotCacheV1 = (*Files)(nil)

// LoadUpdate is collect/port/UpdateStore@v1's.
func (a *Files) LoadUpdate(ctx context.Context) (state.Update, error) {
	return a.loadUpdate(ctx)
}

// SaveUpdate is collect/port/UpdateStore@v1's.
func (a *Files) SaveUpdate(ctx context.Context, u state.Update) error {
	return a.saveUpdate(ctx, u)
}

var _ collector.UpdateStoreV1 = (*Files)(nil)
