// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

package collector

import (
	"context"
	"slices"
	"testing"

	"github.com/kitsunium/statusline/collect/state"
	"github.com/kitsunium/statusline/quota"
	"github.com/kitsunium/statusline/snapshot"
)

// TestCheckUpdateInstallsAndProbesANewerRelease is CheckUpdate's scenario "installs and probes a newer release" (success).
func TestCheckUpdateInstallsAndProbesANewerRelease(t *testing.T) {
	uc, in, then := givenCheckUpdateInstallsAndProbesANewerRelease(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("CheckUpdate: %v, want a success", err)
	}
	then(t, out)
}

// TestCheckUpdateAsksNothingWhenDisabled is CheckUpdate's scenario "asks nothing when disabled" (success).
func TestCheckUpdateAsksNothingWhenDisabled(t *testing.T) {
	uc, in, then := givenCheckUpdateAsksNothingWhenDisabled(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("CheckUpdate: %v, want a success", err)
	}
	then(t, out)
}

// TestCheckUpdateNeverInstallsTheBadVersionAgain is CheckUpdate's scenario "never installs the bad version again" (success).
func TestCheckUpdateNeverInstallsTheBadVersionAgain(t *testing.T) {
	uc, in, then := givenCheckUpdateNeverInstallsTheBadVersionAgain(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("CheckUpdate: %v, want a success", err)
	}
	then(t, out)
}

// TestCheckUpdateRollsBackAReleaseThatFailsItsProbe is CheckUpdate's scenario "rolls back a release that fails its probe" (success).
func TestCheckUpdateRollsBackAReleaseThatFailsItsProbe(t *testing.T) {
	uc, in, then := givenCheckUpdateRollsBackAReleaseThatFailsItsProbe(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("CheckUpdate: %v, want a success", err)
	}
	then(t, out)
}

// TestCollectSnapshotCollectsAndCachesANewKey is CollectSnapshot's scenario "collects and caches a new key" (success).
func TestCollectSnapshotCollectsAndCachesANewKey(t *testing.T) {
	uc, in, then := givenCollectSnapshotCollectsAndCachesANewKey(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("CollectSnapshot: %v, want a success", err)
	}
	then(t, out)
}

// TestCollectSnapshotServesAFreshSnapshotWithoutReadingAnything is CollectSnapshot's scenario "serves a fresh snapshot without reading anything" (success).
func TestCollectSnapshotServesAFreshSnapshotWithoutReadingAnything(t *testing.T) {
	uc, in, then := givenCollectSnapshotServesAFreshSnapshotWithoutReadingAnything(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("CollectSnapshot: %v, want a success", err)
	}
	then(t, out)
}

// TestLatestNetworkServesThePersistedFigures is LatestNetwork's scenario "serves the persisted figures" (success).
func TestLatestNetworkServesThePersistedFigures(t *testing.T) {
	uc, in, then := givenLatestNetworkServesThePersistedFigures(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("LatestNetwork: %v, want a success", err)
	}
	then(t, out)
}

// TestLatestNetworkReadsAStaleSummaryAsUnknown is LatestNetwork's scenario "reads a stale summary as unknown" (success).
func TestLatestNetworkReadsAStaleSummaryAsUnknown(t *testing.T) {
	uc, in, then := givenLatestNetworkReadsAStaleSummaryAsUnknown(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("LatestNetwork: %v, want a success", err)
	}
	then(t, out)
}

// TestRefreshNetworkFetchesWhatIsDue is RefreshNetwork's scenario "fetches what is due" (success).
func TestRefreshNetworkFetchesWhatIsDue(t *testing.T) {
	uc, in, then := givenRefreshNetworkFetchesWhatIsDue(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("RefreshNetwork: %v, want a success", err)
	}
	then(t, out)
}

// TestRefreshNetworkFetchesNothingBeforeItsTtl is RefreshNetwork's scenario "fetches nothing before its ttl" (success).
func TestRefreshNetworkFetchesNothingBeforeItsTtl(t *testing.T) {
	uc, in, then := givenRefreshNetworkFetchesNothingBeforeItsTtl(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("RefreshNetwork: %v, want a success", err)
	}
	then(t, out)
}

// TestRefreshNetworkHonoursARetryAfterAcrossARestart is RefreshNetwork's scenario "honours a retry after across a restart" (success).
func TestRefreshNetworkHonoursARetryAfterAcrossARestart(t *testing.T) {
	uc, in, then := givenRefreshNetworkHonoursARetryAfterAcrossARestart(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("RefreshNetwork: %v, want a success", err)
	}
	then(t, out)
}

// TestRefreshNetworkKeepsTheLastPayloadWithoutAToken is RefreshNetwork's scenario "keeps the last payload without a token" (success).
func TestRefreshNetworkKeepsTheLastPayloadWithoutAToken(t *testing.T) {
	uc, in, then := givenRefreshNetworkKeepsTheLastPayloadWithoutAToken(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("RefreshNetwork: %v, want a success", err)
	}
	then(t, out)
}

// sequenceRecorder wraps the ports a sequence goes through, and records each
// call in order.
type sequenceRecorder struct {
	calls *[]string
}

// RecordCollectorNetworkStoreV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordCollectorNetworkStoreV1(next NetworkStoreV1) NetworkStoreV1 {
	return recordedcollectorNetworkStoreV1{next: next, calls: r.calls}
}

type recordedcollectorNetworkStoreV1 struct {
	next  NetworkStoreV1
	calls *[]string
}

func (x recordedcollectorNetworkStoreV1) LoadNetwork(ctx context.Context) (state.Network, error) {
	*x.calls = append(*x.calls, "collect/port/NetworkStore@v1.LoadNetwork")
	return x.next.LoadNetwork(ctx)
}

func (x recordedcollectorNetworkStoreV1) SaveNetwork(ctx context.Context, n state.Network) error {
	*x.calls = append(*x.calls, "collect/port/NetworkStore@v1.SaveNetwork")
	return x.next.SaveNetwork(ctx, n)
}

// RecordCollectorReleaseSourceV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordCollectorReleaseSourceV1(next ReleaseSourceV1) ReleaseSourceV1 {
	return recordedcollectorReleaseSourceV1{next: next, calls: r.calls}
}

type recordedcollectorReleaseSourceV1 struct {
	next  ReleaseSourceV1
	calls *[]string
}

func (x recordedcollectorReleaseSourceV1) Install(ctx context.Context, rel state.Release) error {
	*x.calls = append(*x.calls, "collect/port/ReleaseSource@v1.Install")
	return x.next.Install(ctx, rel)
}

func (x recordedcollectorReleaseSourceV1) Latest(ctx context.Context) (state.Release, error) {
	*x.calls = append(*x.calls, "collect/port/ReleaseSource@v1.Latest")
	return x.next.Latest(ctx)
}

// RecordCollectorStatusPageV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordCollectorStatusPageV1(next StatusPageV1) StatusPageV1 {
	return recordedcollectorStatusPageV1{next: next, calls: r.calls}
}

type recordedcollectorStatusPageV1 struct {
	next  StatusPageV1
	calls *[]string
}

func (x recordedcollectorStatusPageV1) Fetch(ctx context.Context) (snapshot.Health, error) {
	*x.calls = append(*x.calls, "collect/port/StatusPage@v1.Fetch")
	return x.next.Fetch(ctx)
}

// RecordCollectorTokenStoreV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordCollectorTokenStoreV1(next TokenStoreV1) TokenStoreV1 {
	return recordedcollectorTokenStoreV1{next: next, calls: r.calls}
}

type recordedcollectorTokenStoreV1 struct {
	next  TokenStoreV1
	calls *[]string
}

func (x recordedcollectorTokenStoreV1) Token(ctx context.Context) (string, error) {
	*x.calls = append(*x.calls, "collect/port/TokenStore@v1.Token")
	return x.next.Token(ctx)
}

// RecordCollectorUpdateStoreV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordCollectorUpdateStoreV1(next UpdateStoreV1) UpdateStoreV1 {
	return recordedcollectorUpdateStoreV1{next: next, calls: r.calls}
}

type recordedcollectorUpdateStoreV1 struct {
	next  UpdateStoreV1
	calls *[]string
}

func (x recordedcollectorUpdateStoreV1) LoadUpdate(ctx context.Context) (state.Update, error) {
	*x.calls = append(*x.calls, "collect/port/UpdateStore@v1.LoadUpdate")
	return x.next.LoadUpdate(ctx)
}

func (x recordedcollectorUpdateStoreV1) SaveUpdate(ctx context.Context, u state.Update) error {
	*x.calls = append(*x.calls, "collect/port/UpdateStore@v1.SaveUpdate")
	return x.next.SaveUpdate(ctx, u)
}

// RecordCollectorUsageAPIV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordCollectorUsageAPIV1(next UsageAPIV1) UsageAPIV1 {
	return recordedcollectorUsageAPIV1{next: next, calls: r.calls}
}

type recordedcollectorUsageAPIV1 struct {
	next  UsageAPIV1
	calls *[]string
}

func (x recordedcollectorUsageAPIV1) Fetch(ctx context.Context, token string) (quota.Set, error) {
	*x.calls = append(*x.calls, "collect/port/UsageAPI@v1.Fetch")
	return x.next.Fetch(ctx, token)
}

// TestSequenceRefreshNetwork is the order of sequence refresh-network: the diagram's links, in the
// diagram's order (D21).
func TestSequenceRefreshNetwork(t *testing.T) {
	var got []string
	run := givenSequenceRefreshNetwork(t, sequenceRecorder{calls: &got})
	if err := run(t.Context()); err != nil {
		t.Fatalf("the sequence failed: %v", err)
	}
	want := []string{"collect/port/NetworkStore@v1.LoadNetwork", "collect/port/TokenStore@v1.Token", "collect/port/UsageAPI@v1.Fetch", "collect/port/StatusPage@v1.Fetch", "collect/port/NetworkStore@v1.SaveNetwork"}
	if !slices.Equal(got, want) {
		t.Errorf("the calls: %q, want %q", got, want)
	}
}

// TestSequenceSelfUpdate is the order of sequence self-update: the diagram's links, in the
// diagram's order (D21).
func TestSequenceSelfUpdate(t *testing.T) {
	var got []string
	run := givenSequenceSelfUpdate(t, sequenceRecorder{calls: &got})
	if err := run(t.Context()); err != nil {
		t.Fatalf("the sequence failed: %v", err)
	}
	want := []string{"collect/port/UpdateStore@v1.LoadUpdate", "collect/port/ReleaseSource@v1.Latest", "collect/port/ReleaseSource@v1.Install", "collect/port/UpdateStore@v1.SaveUpdate"}
	if !slices.Equal(got, want) {
		t.Errorf("the calls: %q, want %q", got, want)
	}
}
