// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fd66b2b6a3694bc24ec48192c387084ddcee0ebf9262003e13519df5987eff47

// Package collector — What the daemon does — collect a key's snapshot,
// refresh the network figures, serve the last ones, update the binary — and
// every port it goes through.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package collector

import (
	"context"
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/state"
	"github.com/kitsunium/statusline/ipc"
	"github.com/kitsunium/statusline/quota"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 2, 255), "NOT_IMPLEMENTED", "not implemented yet", "collector: a hand-written body is still a skeleton")

// ClockV1 is an outbound port: the product calls through it.
type ClockV1 interface {
	Now(ctx context.Context) (time.Time, error)
}

// CommandV1 is the daemon role's entry.
type CommandV1 interface {
	Run(ctx context.Context, args []string) error
}

// DaemonV1 is the contract statusline.ipc/v1 as the daemon answers it (D22).
type DaemonV1 interface {
	Snapshot(ctx context.Context, key ipc.Key) (snapshot.Snapshot, error)
	Status(ctx context.Context) (ipc.Status, error)
	Stop(ctx context.Context) error
}

// MCPCallsV1 is an outbound port: the product calls through it.
type MCPCallsV1 interface {
	Busy(ctx context.Context, transcriptPath string, sessionID string, now time.Time) ([]string, error)
}

// MCPConfigV1 is an outbound port: the product calls through it.
type MCPConfigV1 interface {
	Servers(ctx context.Context, projectDir string, hostPID int) (snapshot.MCPServers, error)
}

// NetworkStoreV1 is an outbound port: the product calls through it.
type NetworkStoreV1 interface {
	LoadNetwork(ctx context.Context) (state.Network, error)
	SaveNetwork(ctx context.Context, n state.Network) error
}

// ReleaseSourceV1 is an outbound port: the product calls through it.
type ReleaseSourceV1 interface {
	Install(ctx context.Context, rel state.Release) error
	Latest(ctx context.Context) (state.Release, error)
	Probe(ctx context.Context) error
	Rollback(ctx context.Context) error
}

// RepositoryV1 is an outbound port: the product calls through it.
type RepositoryV1 interface {
	DiffStats(ctx context.Context, dir string) (snapshot.Changes, error)
	Status(ctx context.Context, dir string) (snapshot.GitStatus, error)
}

// SessionCacheV1 keeps the snapshots by key, and when each key was last asked
// for.
type SessionCacheV1 interface {
	Evict(ctx context.Context, now time.Time) (int, error)
	Get(ctx context.Context, key ipc.Key, now time.Time) (snapshot.Snapshot, bool, error)
	LastRequest(ctx context.Context) (time.Time, error)
	Len(ctx context.Context) (int, error)
	Put(ctx context.Context, key ipc.Key, snap snapshot.Snapshot, now time.Time) error
	Touch(ctx context.Context, key ipc.Key, now time.Time) error
}

// SessionRegistryV1 is an outbound port: the product calls through it.
type SessionRegistryV1 interface {
	Lookup(ctx context.Context, sessionID string) (state.HostSession, bool, error)
}

// SnapshotCacheV1 is an outbound port: the product calls through it.
type SnapshotCacheV1 interface {
	SaveSnapshot(ctx context.Context, key ipc.Key, snap snapshot.Snapshot) error
}

// StatusPageV1 is an outbound port: the product calls through it.
type StatusPageV1 interface {
	Fetch(ctx context.Context) (snapshot.Health, error)
}

// SystemInfoV1 is an outbound port: the product calls through it.
type SystemInfoV1 interface {
	Info(ctx context.Context) (snapshot.System, error)
}

// TaskStoreV1 is an outbound port: the product calls through it.
type TaskStoreV1 interface {
	Board(ctx context.Context, sessionID string, listID string, now time.Time) (snapshot.TaskBoard, error)
}

// TokenStoreV1 reads the OAuth token on every call: never cached, refreshed or
// sent anywhere but the usage API.
type TokenStoreV1 interface {
	Token(ctx context.Context) (string, error)
}

// UpdateStoreV1 is an outbound port: the product calls through it.
type UpdateStoreV1 interface {
	LoadUpdate(ctx context.Context) (state.Update, error)
	SaveUpdate(ctx context.Context, u state.Update) error
}

// UsageAPIV1 fetches the quotas once; a 429 is a *state.RateLimited, anything
// else wraps state.ErrUsageUnavailable.
type UsageAPIV1 interface {
	Fetch(ctx context.Context, token string) (quota.Set, error)
}

// WorkDirV1 is an outbound port: the product calls through it.
type WorkDirV1 interface {
	Dir(ctx context.Context, transcriptPath string, fallback string) (string, error)
}

// CheckUpdate — Hourly, never elevated. A newer signed release is installed
// with <bin>.prev kept and probed; a failed probe rolls back and the version
// is never installed again.
type CheckUpdate interface {
	Execute(ctx context.Context, in CheckUpdateInput) (CheckUpdateOutput, error)
}

// CheckUpdateInput is CheckUpdate's input: a field added breaks no caller.
type CheckUpdateInput struct {
	CurrentVersion string
	Disabled       bool
}

// CheckUpdateOutput is CheckUpdate's output.
type CheckUpdateOutput struct {
	Notice    snapshot.UpdateNotice
	Installed bool
}

// CheckUpdateHandler runs CheckUpdate: its body is the hand-written execute.
type CheckUpdateHandler struct {
	clock         ClockV1
	updateStore   UpdateStoreV1
	releaseSource ReleaseSourceV1
}

// NewCheckUpdate builds CheckUpdate on what it calls.
func NewCheckUpdate(clock ClockV1, updateStore UpdateStoreV1, releaseSource ReleaseSourceV1) *CheckUpdateHandler {
	return &CheckUpdateHandler{clock: clock, updateStore: updateStore, releaseSource: releaseSource}
}

// Execute runs CheckUpdate.
func (h *CheckUpdateHandler) Execute(ctx context.Context, in CheckUpdateInput) (CheckUpdateOutput, error) {
	return h.execute(ctx, in)
}

var _ CheckUpdate = (*CheckUpdateHandler)(nil)

// CollectSnapshot — A snapshot younger than state.Freshness is served as is;
// otherwise every source is read — git where the session works, MCP in its
// own directory — kept and cached.
type CollectSnapshot interface {
	Execute(ctx context.Context, in CollectSnapshotInput) (CollectSnapshotOutput, error)
}

// CollectSnapshotInput is CollectSnapshot's input: a field added breaks no caller.
type CollectSnapshotInput struct {
	Key ipc.Key
}

// CollectSnapshotOutput is CollectSnapshot's output.
type CollectSnapshotOutput struct {
	Snapshot  snapshot.Snapshot
	Collected bool
}

// CollectSnapshotHandler runs CollectSnapshot: its body is the hand-written execute.
type CollectSnapshotHandler struct {
	clock           ClockV1
	sessionCache    SessionCacheV1
	workDir         WorkDirV1
	sessionRegistry SessionRegistryV1
	repository      RepositoryV1
	systemInfo      SystemInfoV1
	mcpCalls        MCPCallsV1
	mcpConfig       MCPConfigV1
	taskStore       TaskStoreV1
	latestNetwork   LatestNetwork
	snapshotCache   SnapshotCacheV1
}

// NewCollectSnapshot builds CollectSnapshot on what it calls.
func NewCollectSnapshot(clock ClockV1, sessionCache SessionCacheV1, workDir WorkDirV1, sessionRegistry SessionRegistryV1, repository RepositoryV1, systemInfo SystemInfoV1, mcpCalls MCPCallsV1, mcpConfig MCPConfigV1, taskStore TaskStoreV1, latestNetwork LatestNetwork, snapshotCache SnapshotCacheV1) *CollectSnapshotHandler {
	return &CollectSnapshotHandler{clock: clock, sessionCache: sessionCache, workDir: workDir, sessionRegistry: sessionRegistry, repository: repository, systemInfo: systemInfo, mcpCalls: mcpCalls, mcpConfig: mcpConfig, taskStore: taskStore, latestNetwork: latestNetwork, snapshotCache: snapshotCache}
}

// Execute runs CollectSnapshot.
func (h *CollectSnapshotHandler) Execute(ctx context.Context, in CollectSnapshotInput) (CollectSnapshotOutput, error) {
	return h.execute(ctx, in)
}

var _ CollectSnapshot = (*CollectSnapshotHandler)(nil)

// LatestNetwork — The last figures; the health unknown past
// state.HealthMaxAge.
type LatestNetwork interface {
	Execute(ctx context.Context, in LatestNetworkInput) (LatestNetworkOutput, error)
}

// LatestNetworkInput is LatestNetwork's input: a field added breaks no caller.
type LatestNetworkInput struct {
}

// LatestNetworkOutput is LatestNetwork's output.
type LatestNetworkOutput struct {
	Usage    quota.Set
	HasUsage bool
	Health   snapshot.Health
	Network  state.Network
}

// LatestNetworkHandler runs LatestNetwork: its body is the hand-written execute.
type LatestNetworkHandler struct {
	clock        ClockV1
	networkStore NetworkStoreV1
}

// NewLatestNetwork builds LatestNetwork on what it calls.
func NewLatestNetwork(clock ClockV1, networkStore NetworkStoreV1) *LatestNetworkHandler {
	return &LatestNetworkHandler{clock: clock, networkStore: networkStore}
}

// Execute runs LatestNetwork.
func (h *LatestNetworkHandler) Execute(ctx context.Context, in LatestNetworkInput) (LatestNetworkOutput, error) {
	return h.execute(ctx, in)
}

var _ LatestNetwork = (*LatestNetworkHandler)(nil)

// RefreshNetwork — Fetches what is due — the usage API at most once a
// UsageTTL and never before a Retry-After, the status page once a HealthTTL
// — and persists the bookkeeping after any attempt.
type RefreshNetwork interface {
	Execute(ctx context.Context, in RefreshNetworkInput) (RefreshNetworkOutput, error)
}

// RefreshNetworkInput is RefreshNetwork's input: a field added breaks no caller.
type RefreshNetworkInput struct {
	Force bool
}

// RefreshNetworkOutput is RefreshNetwork's output.
type RefreshNetworkOutput struct {
	UsageFetched  bool
	HealthFetched bool
}

// RefreshNetworkHandler runs RefreshNetwork: its body is the hand-written execute.
type RefreshNetworkHandler struct {
	clock        ClockV1
	networkStore NetworkStoreV1
	tokenStore   TokenStoreV1
	usageAPI     UsageAPIV1
	statusPage   StatusPageV1
}

// NewRefreshNetwork builds RefreshNetwork on what it calls.
func NewRefreshNetwork(clock ClockV1, networkStore NetworkStoreV1, tokenStore TokenStoreV1, usageAPI UsageAPIV1, statusPage StatusPageV1) *RefreshNetworkHandler {
	return &RefreshNetworkHandler{clock: clock, networkStore: networkStore, tokenStore: tokenStore, usageAPI: usageAPI, statusPage: statusPage}
}

// Execute runs RefreshNetwork.
func (h *RefreshNetworkHandler) Execute(ctx context.Context, in RefreshNetworkInput) (RefreshNetworkOutput, error) {
	return h.execute(ctx, in)
}

var _ RefreshNetwork = (*RefreshNetworkHandler)(nil)
