// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package snapshot — What the daemon collects for one session and the client
// renders.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package snapshot

import (
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/quota"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 1, 2, 255), "NOT_IMPLEMENTED", "not implemented yet", "snapshot: a hand-written body is still a skeleton")

const (
	// HealthDegraded is a constant of the design.
	HealthDegraded int = 2
	// HealthDown is a constant of the design.
	HealthDown int = 3
	// HealthOK is a constant of the design.
	HealthOK int = 1
	// HealthUnknown is a constant of the design.
	HealthUnknown int = 0
	// MCPSourceCLI is a constant of the design.
	MCPSourceCLI string = "cli"
	// MCPSourceLocal is a constant of the design.
	MCPSourceLocal string = "local"
	// MCPSourceManaged is a constant of the design.
	MCPSourceManaged string = "managed"
	// MCPSourcePlugin is a constant of the design.
	MCPSourcePlugin string = "plugin"
	// MCPSourceProject is a constant of the design.
	MCPSourceProject string = "project"
	// MCPSourceUnknown is a constant of the design.
	MCPSourceUnknown string = ""
	// MCPSourceUser is a constant of the design.
	MCPSourceUser string = "user"
	// NoEpic is the epic of tasks tied to none.
	NoEpic int = 0
	// OSDarwin is a constant of the design.
	OSDarwin int = 1
	// OSLinux is a constant of the design.
	OSLinux int = 0
	// OSUnknown is a constant of the design.
	OSUnknown int = 3
	// OSWindows is a constant of the design.
	OSWindows int = 2
	// TaskCompleted is a constant of the design.
	TaskCompleted string = "completed"
	// TaskInProgress is a constant of the design.
	TaskInProgress string = "in_progress"
	// TaskPending is a constant of the design.
	TaskPending string = "pending"
	// TaskWaiting is a constant of the design.
	TaskWaiting string = "waiting"
)

// Changes is a value object of the design.
type Changes struct {
	Added   int `json:"added,omitempty"`
	Removed int `json:"removed,omitempty"`
}

// HasAdded is a method of the design.
func (c Changes) HasAdded() bool {
	return c.hasAdded()
}

// HasChanges is a method of the design.
func (c Changes) HasChanges() bool {
	return c.hasChanges()
}

// HasRemoved is a method of the design.
func (c Changes) HasRemoved() bool {
	return c.hasRemoved()
}

// Epic is a value object of the design.
type Epic struct {
	ID        int      `json:"id"`
	Title     string   `json:"title,omitempty"`
	Active    bool     `json:"active,omitempty"`
	Tasks     TaskList `json:"tasks"`
	Subagents int      `json:"subagents,omitempty"`
}

// GitStatus is a value object of the design.
type GitStatus struct {
	Branch    string `json:"branch,omitempty"`
	Modified  int    `json:"modified,omitempty"`
	Untracked int    `json:"untracked,omitempty"`
	Worktrees int    `json:"worktrees,omitempty"`
}

// IsInRepo is a method of the design.
func (g GitStatus) IsInRepo() bool {
	return g.isInRepo()
}

// MCPServer is a value object of the design.
type MCPServer struct {
	Name    string `json:"name"`
	Enabled bool   `json:"enabled,omitempty"`
	Plugin  string `json:"plugin,omitempty"`
	Source  string `json:"source,omitempty"`
	Busy    bool   `json:"busy,omitempty"`
}

// Snapshot — Everything collected for one session key.
type Snapshot struct {
	WorkDir     string       `json:"work_dir,omitempty"`
	Git         GitStatus    `json:"git"`
	Changes     Changes      `json:"changes"`
	MCP         []MCPServer  `json:"mcp,omitempty"`
	Tasks       TaskBoard    `json:"tasks"`
	Working     bool         `json:"working,omitempty"`
	System      System       `json:"system"`
	Health      int          `json:"health,omitempty"`
	API         quota.Set    `json:"api"`
	Update      UpdateNotice `json:"update"`
	CollectedAt time.Time    `json:"collected_at"`
}

// System is a value object of the design.
type System struct {
	OS       int  `json:"os"`
	IsDocker bool `json:"docker,omitempty"`
}

// TaskBoard is a value object of the design.
type TaskBoard struct {
	Epics        []Epic `json:"epics,omitempty"`
	Unattributed int    `json:"unattributed,omitempty"`
}

// IsEmpty is a method of the design.
func (tx TaskBoard) IsEmpty() bool {
	return tx.isEmpty()
}

// TaskItem is a value object of the design.
type TaskItem struct {
	ID      string `json:"id"`
	Subject string `json:"subject,omitempty"`
	Status  string `json:"status,omitempty"`
}

// TaskList is a value object of the design.
type TaskList struct {
	Items []TaskItem `json:"items,omitempty"`
}

// Active is a method of the design.
func (tx TaskList) Active() int {
	return tx.active()
}

// Current is a method of the design.
func (tx TaskList) Current() string {
	return tx.current()
}

// Done is a method of the design.
func (tx TaskList) Done() int {
	return tx.done()
}

// Headline is a method of the design.
func (tx TaskList) Headline() (string, string) {
	return tx.headline()
}

// IsActive is a method of the design.
func (tx TaskList) IsActive() bool {
	return tx.isActive()
}

// Total is a method of the design.
func (tx TaskList) Total() int {
	return tx.total()
}

// Waiting is a method of the design.
func (tx TaskList) Waiting() int {
	return tx.waiting()
}

// UpdateNotice is a value object of the design.
type UpdateNotice struct {
	Available bool   `json:"available,omitempty"`
	Version   string `json:"version,omitempty"`
}

// ClassifyHealth is a function of the design.
func ClassifyHealth(states []string) int {
	return classifyHealth(states)
}

// ToolKey is a function of the design.
func ToolKey(name string) string {
	return toolKey(name)
}

// WithBusy returns a copy with the servers being called lit, unknown ones
// appended.
func WithBusy(servers []MCPServer, keys []string) []MCPServer {
	return withBusy(servers, keys)
}

// WithSource tags every server with its scope, in place.
func WithSource(servers []MCPServer, source string) []MCPServer {
	return withSource(servers, source)
}
