// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package snapshot

import (
	"hash/fnv"
	"os"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// TestPropertyChangesHasAddedPositive holds status/Changes.HasAdded by property Positive.
func TestPropertyChangesHasAddedPositive(t *testing.T) {
	propertyChangesHasAddedPositive(t, designSeed("status/Changes.HasAdded#Positive"))
}

// TestPropertyChangesHasChangesEitherSide holds status/Changes.HasChanges by property EitherSide.
func TestPropertyChangesHasChangesEitherSide(t *testing.T) {
	propertyChangesHasChangesEitherSide(t, designSeed("status/Changes.HasChanges#EitherSide"))
}

// TestPropertyChangesHasRemovedPositive holds status/Changes.HasRemoved by property Positive.
func TestPropertyChangesHasRemovedPositive(t *testing.T) {
	propertyChangesHasRemovedPositive(t, designSeed("status/Changes.HasRemoved#Positive"))
}

// TestPropertyGitStatusIsInRepoMatchesBranch holds status/GitStatus.IsInRepo by property MatchesBranch.
func TestPropertyGitStatusIsInRepoMatchesBranch(t *testing.T) {
	propertyGitStatusIsInRepoMatchesBranch(t, designSeed("status/GitStatus.IsInRepo#MatchesBranch"))
}

// TestPropertyTaskBoardIsEmptyMatchesContent holds status/TaskBoard.IsEmpty by property MatchesContent.
func TestPropertyTaskBoardIsEmptyMatchesContent(t *testing.T) {
	propertyTaskBoardIsEmptyMatchesContent(t, designSeed("status/TaskBoard.IsEmpty#MatchesContent"))
}

// TestPropertyTaskListActiveCountsInProgress holds status/TaskList.Active by property CountsInProgress.
func TestPropertyTaskListActiveCountsInProgress(t *testing.T) {
	propertyTaskListActiveCountsInProgress(t, designSeed("status/TaskList.Active#CountsInProgress"))
}

// TestPropertyTaskListCurrentInProgressOnly holds status/TaskList.Current by property InProgressOnly.
func TestPropertyTaskListCurrentInProgressOnly(t *testing.T) {
	propertyTaskListCurrentInProgressOnly(t, designSeed("status/TaskList.Current#InProgressOnly"))
}

// TestPropertyTaskListDoneCountsBounded holds status/TaskList.Done by property CountsBounded.
func TestPropertyTaskListDoneCountsBounded(t *testing.T) {
	propertyTaskListDoneCountsBounded(t, designSeed("status/TaskList.Done#CountsBounded"))
}

// TestPropertyTaskListHeadlineNeverCompleted holds status/TaskList.Headline by property NeverCompleted.
func TestPropertyTaskListHeadlineNeverCompleted(t *testing.T) {
	propertyTaskListHeadlineNeverCompleted(t, designSeed("status/TaskList.Headline#NeverCompleted"))
}

// TestPropertyTaskListIsActiveMatchesCounts holds status/TaskList.IsActive by property MatchesCounts.
func TestPropertyTaskListIsActiveMatchesCounts(t *testing.T) {
	propertyTaskListIsActiveMatchesCounts(t, designSeed("status/TaskList.IsActive#MatchesCounts"))
}

// TestPropertyTaskListTotalCountsItems holds status/TaskList.Total by property CountsItems.
func TestPropertyTaskListTotalCountsItems(t *testing.T) {
	propertyTaskListTotalCountsItems(t, designSeed("status/TaskList.Total#CountsItems"))
}

// TestPropertyTaskListWaitingCountsWaiting holds status/TaskList.Waiting by property CountsWaiting.
func TestPropertyTaskListWaitingCountsWaiting(t *testing.T) {
	propertyTaskListWaitingCountsWaiting(t, designSeed("status/TaskList.Waiting#CountsWaiting"))
}

// TestPropertyClassifyHealthMonotonic holds status/function/ClassifyHealth by property Monotonic.
func TestPropertyClassifyHealthMonotonic(t *testing.T) {
	propertyClassifyHealthMonotonic(t, designSeed("status/function/ClassifyHealth#Monotonic"))
}

// TestPropertyToolKeyCharset holds status/function/ToolKey by property Charset.
func TestPropertyToolKeyCharset(t *testing.T) {
	propertyToolKeyCharset(t, designSeed("status/function/ToolKey#Charset"))
}

// TestPropertyWithBusyKeepsServers holds status/function/WithBusy by property KeepsServers.
func TestPropertyWithBusyKeepsServers(t *testing.T) {
	propertyWithBusyKeepsServers(t, designSeed("status/function/WithBusy#KeepsServers"))
}

// TestPropertyWithSourceTagsEvery holds status/function/WithSource by property TagsEvery.
func TestPropertyWithSourceTagsEvery(t *testing.T) {
	propertyWithSourceTagsEvery(t, designSeed("status/function/WithSource#TagsEvery"))
}
