// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

package snapshot

import (
	"flag"
	"hash/fnv"
	"os"
	"strconv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// useSeed logs a property's seed and hands it to pgregory.net/rapid, whose
// only public way in is its -rapid.seed flag: rapid.Check then draws the same
// values in every run of the same design — and in kit test -seed's.
func useSeed(t *testing.T, seed uint64) {
	t.Helper()
	t.Logf("property seed %d (go test -rapid.seed=%d replays it)", seed, seed)
	if f := flag.Lookup("rapid.seed"); f != nil {
		_ = f.Value.Set(strconv.FormatUint(seed, 10))
	}
}

// TestPropertyChangesHasAddedPositive holds status/Changes.HasAdded by property Positive.
func TestPropertyChangesHasAddedPositive(t *testing.T) {
	seed := designSeed("status/Changes.HasAdded#Positive")
	useSeed(t, seed)
	propertyChangesHasAddedPositive(t, seed)
}

// TestPropertyChangesHasChangesEitherSide holds status/Changes.HasChanges by property EitherSide.
func TestPropertyChangesHasChangesEitherSide(t *testing.T) {
	seed := designSeed("status/Changes.HasChanges#EitherSide")
	useSeed(t, seed)
	propertyChangesHasChangesEitherSide(t, seed)
}

// TestPropertyChangesHasRemovedPositive holds status/Changes.HasRemoved by property Positive.
func TestPropertyChangesHasRemovedPositive(t *testing.T) {
	seed := designSeed("status/Changes.HasRemoved#Positive")
	useSeed(t, seed)
	propertyChangesHasRemovedPositive(t, seed)
}

// TestPropertyGitStatusIsInRepoMatchesBranch holds status/GitStatus.IsInRepo by property MatchesBranch.
func TestPropertyGitStatusIsInRepoMatchesBranch(t *testing.T) {
	seed := designSeed("status/GitStatus.IsInRepo#MatchesBranch")
	useSeed(t, seed)
	propertyGitStatusIsInRepoMatchesBranch(t, seed)
}

// TestPropertyMCPServersWithBusyKeepsServers holds status/MCPServers.WithBusy by property KeepsServers.
func TestPropertyMCPServersWithBusyKeepsServers(t *testing.T) {
	seed := designSeed("status/MCPServers.WithBusy#KeepsServers")
	useSeed(t, seed)
	propertyMCPServersWithBusyKeepsServers(t, seed)
}

// TestPropertyMCPServersWithSourceTagsEvery holds status/MCPServers.WithSource by property TagsEvery.
func TestPropertyMCPServersWithSourceTagsEvery(t *testing.T) {
	seed := designSeed("status/MCPServers.WithSource#TagsEvery")
	useSeed(t, seed)
	propertyMCPServersWithSourceTagsEvery(t, seed)
}

// TestPropertyTaskBoardIsEmptyMatchesContent holds status/TaskBoard.IsEmpty by property MatchesContent.
func TestPropertyTaskBoardIsEmptyMatchesContent(t *testing.T) {
	seed := designSeed("status/TaskBoard.IsEmpty#MatchesContent")
	useSeed(t, seed)
	propertyTaskBoardIsEmptyMatchesContent(t, seed)
}

// TestPropertyTaskListActiveCountsInProgress holds status/TaskList.Active by property CountsInProgress.
func TestPropertyTaskListActiveCountsInProgress(t *testing.T) {
	seed := designSeed("status/TaskList.Active#CountsInProgress")
	useSeed(t, seed)
	propertyTaskListActiveCountsInProgress(t, seed)
}

// TestPropertyTaskListCurrentInProgressOnly holds status/TaskList.Current by property InProgressOnly.
func TestPropertyTaskListCurrentInProgressOnly(t *testing.T) {
	seed := designSeed("status/TaskList.Current#InProgressOnly")
	useSeed(t, seed)
	propertyTaskListCurrentInProgressOnly(t, seed)
}

// TestPropertyTaskListDoneCountsBounded holds status/TaskList.Done by property CountsBounded.
func TestPropertyTaskListDoneCountsBounded(t *testing.T) {
	seed := designSeed("status/TaskList.Done#CountsBounded")
	useSeed(t, seed)
	propertyTaskListDoneCountsBounded(t, seed)
}

// TestPropertyTaskListHeadlineNeverCompleted holds status/TaskList.Headline by property NeverCompleted.
func TestPropertyTaskListHeadlineNeverCompleted(t *testing.T) {
	seed := designSeed("status/TaskList.Headline#NeverCompleted")
	useSeed(t, seed)
	propertyTaskListHeadlineNeverCompleted(t, seed)
}

// TestPropertyTaskListIsActiveMatchesCounts holds status/TaskList.IsActive by property MatchesCounts.
func TestPropertyTaskListIsActiveMatchesCounts(t *testing.T) {
	seed := designSeed("status/TaskList.IsActive#MatchesCounts")
	useSeed(t, seed)
	propertyTaskListIsActiveMatchesCounts(t, seed)
}

// TestPropertyTaskListTotalCountsItems holds status/TaskList.Total by property CountsItems.
func TestPropertyTaskListTotalCountsItems(t *testing.T) {
	seed := designSeed("status/TaskList.Total#CountsItems")
	useSeed(t, seed)
	propertyTaskListTotalCountsItems(t, seed)
}

// TestPropertyTaskListWaitingCountsWaiting holds status/TaskList.Waiting by property CountsWaiting.
func TestPropertyTaskListWaitingCountsWaiting(t *testing.T) {
	seed := designSeed("status/TaskList.Waiting#CountsWaiting")
	useSeed(t, seed)
	propertyTaskListWaitingCountsWaiting(t, seed)
}

// TestPropertyClassifyHealthMonotonic holds status/function/ClassifyHealth by property Monotonic.
func TestPropertyClassifyHealthMonotonic(t *testing.T) {
	seed := designSeed("status/function/ClassifyHealth#Monotonic")
	useSeed(t, seed)
	propertyClassifyHealthMonotonic(t, seed)
}

// TestPropertyToolKeyCharset holds status/function/ToolKey by property Charset.
func TestPropertyToolKeyCharset(t *testing.T) {
	seed := designSeed("status/function/ToolKey#Charset")
	useSeed(t, seed)
	propertyToolKeyCharset(t, seed)
}
