// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package powerline — The Powerline renderer — segments, palette, glyphs,
// visible width, the condensing of line one. Its display variables are read by
// its body, once per process.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package powerline

import (
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/quota"
	"github.com/kitsunium/statusline/render/session"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 2, 2, 255), "NOT_IMPLEMENTED", "not implemented yet", "powerline: a hand-written body is still a skeleton")

// Frame — Everything one render draws; Now is the instant countdowns, burn
// cursors and the task pulse are drawn at.
type Frame struct {
	Model       session.ModelInfo
	Effort      string
	FastMode    bool
	SessionName string
	Cost        float64
	Limits      quota.Set
	Icons       Icons
	Width       int
	Dir         string
	Git         snapshot.GitStatus
	Changes     snapshot.Changes
	System      snapshot.System
	MCP         []snapshot.MCPServer
	Health      int
	Tasks       snapshot.TaskBoard
	Working     bool
	Update      snapshot.UpdateNotice
	Now         time.Time
}

// Icons is a value object of the design.
type Icons struct {
	OS    bool
	Path  bool
	Git   bool
	Model bool
}

// Condensed is a function of the design.
func Condensed(frame Frame) []string {
	return condensed(frame)
}

// IconsFromEnv is a function of the design.
func IconsFromEnv(env map[string]string) Icons {
	return iconsFromEnv(env)
}

// ParseWidth is a function of the design.
func ParseWidth(value string) int {
	return parseWidth(value)
}

// Render is a function of the design.
func Render(frame Frame) string {
	return render(frame)
}

// VisibleWidth is a function of the design.
func VisibleWidth(s string) int {
	return visibleWidth(s)
}
