// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package powerline

import (
	"hash/fnv"
	"os"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// TestPropertyCondensedMonotonic holds render/function/Condensed by property Monotonic.
func TestPropertyCondensedMonotonic(t *testing.T) {
	propertyCondensedMonotonic(t, designSeed("render/function/Condensed#Monotonic"))
}

// TestPropertyIconsFromEnvOnlyNegativesSwitchOff holds render/function/IconsFromEnv by property OnlyNegativesSwitchOff.
func TestPropertyIconsFromEnvOnlyNegativesSwitchOff(t *testing.T) {
	propertyIconsFromEnvOnlyNegativesSwitchOff(t, designSeed("render/function/IconsFromEnv#OnlyNegativesSwitchOff"))
}

// TestPropertyParseWidthBounded holds render/function/ParseWidth by property Bounded.
func TestPropertyParseWidthBounded(t *testing.T) {
	propertyParseWidthBounded(t, designSeed("render/function/ParseWidth#Bounded"))
}

// TestPropertyRenderTwoLines holds render/function/Render by property TwoLines.
func TestPropertyRenderTwoLines(t *testing.T) {
	propertyRenderTwoLines(t, designSeed("render/function/Render#TwoLines"))
}

// TestPropertyRenderLineOneFits holds render/function/Render by property LineOneFits.
func TestPropertyRenderLineOneFits(t *testing.T) {
	propertyRenderLineOneFits(t, designSeed("render/function/Render#LineOneFits"))
}

// TestPropertyVisibleWidthIgnoresEscapes holds render/function/VisibleWidth by property IgnoresEscapes.
func TestPropertyVisibleWidthIgnoresEscapes(t *testing.T) {
	propertyVisibleWidthIgnoresEscapes(t, designSeed("render/function/VisibleWidth#IgnoresEscapes"))
}

// TestPropertyVisibleWidthAdditive holds render/function/VisibleWidth by property Additive.
func TestPropertyVisibleWidthAdditive(t *testing.T) {
	propertyVisibleWidthAdditive(t, designSeed("render/function/VisibleWidth#Additive"))
}
