// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package quota

import (
	"hash/fnv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path))
	return h.Sum64()
}

// TestPropertyExtraIsValidRequiresEnabled holds status/Extra.IsValid by property RequiresEnabled.
func TestPropertyExtraIsValidRequiresEnabled(t *testing.T) {
	propertyExtraIsValidRequiresEnabled(t, designSeed("status/Extra.IsValid#RequiresEnabled"))
}

// TestPropertyLimitCursorPositionBounded holds status/Limit.CursorPosition by property Bounded.
func TestPropertyLimitCursorPositionBounded(t *testing.T) {
	propertyLimitCursorPositionBounded(t, designSeed("status/Limit.CursorPosition#Bounded"))
}

// TestPropertyLimitElapsedBounded holds status/Limit.Elapsed by property Bounded.
func TestPropertyLimitElapsedBounded(t *testing.T) {
	propertyLimitElapsedBounded(t, designSeed("status/Limit.Elapsed#Bounded"))
}

// TestPropertyLimitExhaustsInBeforeReset holds status/Limit.ExhaustsIn by property BeforeReset.
func TestPropertyLimitExhaustsInBeforeReset(t *testing.T) {
	propertyLimitExhaustsInBeforeReset(t, designSeed("status/Limit.ExhaustsIn#BeforeReset"))
}

// TestPropertyLimitHasWindowNeedsBoth holds status/Limit.HasWindow by property NeedsBoth.
func TestPropertyLimitHasWindowNeedsBoth(t *testing.T) {
	propertyLimitHasWindowNeedsBoth(t, designSeed("status/Limit.HasWindow#NeedsBoth"))
}

// TestPropertyLimitIsOnTrackMatchesPace holds status/Limit.IsOnTrack by property MatchesPace.
func TestPropertyLimitIsOnTrackMatchesPace(t *testing.T) {
	propertyLimitIsOnTrackMatchesPace(t, designSeed("status/Limit.IsOnTrack#MatchesPace"))
}

// TestPropertyLimitIsValidNeedsSource holds status/Limit.IsValid by property NeedsSource.
func TestPropertyLimitIsValidNeedsSource(t *testing.T) {
	propertyLimitIsValidNeedsSource(t, designSeed("status/Limit.IsValid#NeedsSource"))
}

// TestPropertyLimitPaceAgainstCursor holds status/Limit.Pace by property AgainstCursor.
func TestPropertyLimitPaceAgainstCursor(t *testing.T) {
	propertyLimitPaceAgainstCursor(t, designSeed("status/Limit.Pace#AgainstCursor"))
}

// TestPropertyLimitProgressKeepsPercent holds status/Limit.Progress by property KeepsPercent.
func TestPropertyLimitProgressKeepsPercent(t *testing.T) {
	propertyLimitProgressKeepsPercent(t, designSeed("status/Limit.Progress#KeepsPercent"))
}

// TestPropertyLimitProjectedNonNegative holds status/Limit.Projected by property NonNegative.
func TestPropertyLimitProjectedNonNegative(t *testing.T) {
	propertyLimitProjectedNonNegative(t, designSeed("status/Limit.Projected#NonNegative"))
}

// TestPropertyLimitRemainingNeverNegative holds status/Limit.Remaining by property NeverNegative.
func TestPropertyLimitRemainingNeverNegative(t *testing.T) {
	propertyLimitRemainingNeverNegative(t, designSeed("status/Limit.Remaining#NeverNegative"))
}

// TestPropertyProgressLevelMonotonic holds status/Progress.Level by property Monotonic.
func TestPropertyProgressLevelMonotonic(t *testing.T) {
	propertyProgressLevelMonotonic(t, designSeed("status/Progress.Level#Monotonic"))
}

// TestPropertySetHasTimedMatchesTimed holds status/Set.HasTimed by property MatchesTimed.
func TestPropertySetHasTimedMatchesTimed(t *testing.T) {
	propertySetHasTimedMatchesTimed(t, designSeed("status/Set.HasTimed#MatchesTimed"))
}

// TestPropertySetScopedForSubsetOfScoped holds status/Set.ScopedFor by property SubsetOfScoped.
func TestPropertySetScopedForSubsetOfScoped(t *testing.T) {
	propertySetScopedForSubsetOfScoped(t, designSeed("status/Set.ScopedFor#SubsetOfScoped"))
}

// TestPropertySetTimedOnlyValid holds status/Set.Timed by property OnlyValid.
func TestPropertySetTimedOnlyValid(t *testing.T) {
	propertySetTimedOnlyValid(t, designSeed("status/Set.Timed#OnlyValid"))
}

// TestPropertyNewLimitPercentClamped holds status/function/NewLimit by property PercentClamped.
func TestPropertyNewLimitPercentClamped(t *testing.T) {
	propertyNewLimitPercentClamped(t, designSeed("status/function/NewLimit#PercentClamped"))
}

// TestPropertyNewProgressBounded holds status/function/NewProgress by property Bounded.
func TestPropertyNewProgressBounded(t *testing.T) {
	propertyNewProgressBounded(t, designSeed("status/function/NewProgress#Bounded"))
}

// TestPropertyResolveStdinWins holds status/function/Resolve by property StdinWins.
func TestPropertyResolveStdinWins(t *testing.T) {
	propertyResolveStdinWins(t, designSeed("status/function/Resolve#StdinWins"))
}

// TestPropertyResolveNeverInvents holds status/function/Resolve by property NeverInvents.
func TestPropertyResolveNeverInvents(t *testing.T) {
	propertyResolveNeverInvents(t, designSeed("status/function/Resolve#NeverInvents"))
}
