// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fd66b2b6a3694bc24ec48192c387084ddcee0ebf9262003e13519df5987eff47

package quota

import (
	"flag"
	"hash/fnv"
	"os"
	"strconv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:fd66b2b6a3694bc24ec48192c387084ddcee0ebf9262003e13519df5987eff47"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// useSeed logs a property's seed and hands it to pgregory.net/rapid, whose
// only public way in is its -rapid.seed flag: rapid.Check then draws the same
// values in every run of the same design — and in kit test -seed's.
func useSeed(t *testing.T, seed uint64) {
	t.Helper()
	t.Logf("property seed %d (go test -rapid.seed=%d replays it)", seed, seed)
	if f := flag.Lookup("rapid.seed"); f != nil {
		_ = f.Value.Set(strconv.FormatUint(seed, 10))
	}
}

// TestPropertyExtraIsValidRequiresEnabled holds status/Extra.IsValid by property RequiresEnabled.
func TestPropertyExtraIsValidRequiresEnabled(t *testing.T) {
	seed := designSeed("status/Extra.IsValid#RequiresEnabled")
	useSeed(t, seed)
	propertyExtraIsValidRequiresEnabled(t, seed)
}

// TestPropertyLimitCursorPositionBounded holds status/Limit.CursorPosition by property Bounded.
func TestPropertyLimitCursorPositionBounded(t *testing.T) {
	seed := designSeed("status/Limit.CursorPosition#Bounded")
	useSeed(t, seed)
	propertyLimitCursorPositionBounded(t, seed)
}

// TestPropertyLimitElapsedBounded holds status/Limit.Elapsed by property Bounded.
func TestPropertyLimitElapsedBounded(t *testing.T) {
	seed := designSeed("status/Limit.Elapsed#Bounded")
	useSeed(t, seed)
	propertyLimitElapsedBounded(t, seed)
}

// TestPropertyLimitExhaustsInBeforeReset holds status/Limit.ExhaustsIn by property BeforeReset.
func TestPropertyLimitExhaustsInBeforeReset(t *testing.T) {
	seed := designSeed("status/Limit.ExhaustsIn#BeforeReset")
	useSeed(t, seed)
	propertyLimitExhaustsInBeforeReset(t, seed)
}

// TestPropertyLimitHasWindowNeedsBoth holds status/Limit.HasWindow by property NeedsBoth.
func TestPropertyLimitHasWindowNeedsBoth(t *testing.T) {
	seed := designSeed("status/Limit.HasWindow#NeedsBoth")
	useSeed(t, seed)
	propertyLimitHasWindowNeedsBoth(t, seed)
}

// TestPropertyLimitIsOnTrackMatchesPace holds status/Limit.IsOnTrack by property MatchesPace.
func TestPropertyLimitIsOnTrackMatchesPace(t *testing.T) {
	seed := designSeed("status/Limit.IsOnTrack#MatchesPace")
	useSeed(t, seed)
	propertyLimitIsOnTrackMatchesPace(t, seed)
}

// TestPropertyLimitIsValidNeedsSource holds status/Limit.IsValid by property NeedsSource.
func TestPropertyLimitIsValidNeedsSource(t *testing.T) {
	seed := designSeed("status/Limit.IsValid#NeedsSource")
	useSeed(t, seed)
	propertyLimitIsValidNeedsSource(t, seed)
}

// TestPropertyLimitPaceAgainstCursor holds status/Limit.Pace by property AgainstCursor.
func TestPropertyLimitPaceAgainstCursor(t *testing.T) {
	seed := designSeed("status/Limit.Pace#AgainstCursor")
	useSeed(t, seed)
	propertyLimitPaceAgainstCursor(t, seed)
}

// TestPropertyLimitProgressKeepsPercent holds status/Limit.Progress by property KeepsPercent.
func TestPropertyLimitProgressKeepsPercent(t *testing.T) {
	seed := designSeed("status/Limit.Progress#KeepsPercent")
	useSeed(t, seed)
	propertyLimitProgressKeepsPercent(t, seed)
}

// TestPropertyLimitProjectedNonNegative holds status/Limit.Projected by property NonNegative.
func TestPropertyLimitProjectedNonNegative(t *testing.T) {
	seed := designSeed("status/Limit.Projected#NonNegative")
	useSeed(t, seed)
	propertyLimitProjectedNonNegative(t, seed)
}

// TestPropertyLimitRemainingNeverNegative holds status/Limit.Remaining by property NeverNegative.
func TestPropertyLimitRemainingNeverNegative(t *testing.T) {
	seed := designSeed("status/Limit.Remaining#NeverNegative")
	useSeed(t, seed)
	propertyLimitRemainingNeverNegative(t, seed)
}

// TestPropertyProgressLevelMonotonic holds status/Progress.Level by property Monotonic.
func TestPropertyProgressLevelMonotonic(t *testing.T) {
	seed := designSeed("status/Progress.Level#Monotonic")
	useSeed(t, seed)
	propertyProgressLevelMonotonic(t, seed)
}

// TestPropertySetHasTimedMatchesTimed holds status/Set.HasTimed by property MatchesTimed.
func TestPropertySetHasTimedMatchesTimed(t *testing.T) {
	seed := designSeed("status/Set.HasTimed#MatchesTimed")
	useSeed(t, seed)
	propertySetHasTimedMatchesTimed(t, seed)
}

// TestPropertySetScopedForSubsetOfScoped holds status/Set.ScopedFor by property SubsetOfScoped.
func TestPropertySetScopedForSubsetOfScoped(t *testing.T) {
	seed := designSeed("status/Set.ScopedFor#SubsetOfScoped")
	useSeed(t, seed)
	propertySetScopedForSubsetOfScoped(t, seed)
}

// TestPropertySetTimedOnlyValid holds status/Set.Timed by property OnlyValid.
func TestPropertySetTimedOnlyValid(t *testing.T) {
	seed := designSeed("status/Set.Timed#OnlyValid")
	useSeed(t, seed)
	propertySetTimedOnlyValid(t, seed)
}

// TestPropertyNewLimitPercentClamped holds status/function/NewLimit by property PercentClamped.
func TestPropertyNewLimitPercentClamped(t *testing.T) {
	seed := designSeed("status/function/NewLimit#PercentClamped")
	useSeed(t, seed)
	propertyNewLimitPercentClamped(t, seed)
}

// TestPropertyNewProgressBounded holds status/function/NewProgress by property Bounded.
func TestPropertyNewProgressBounded(t *testing.T) {
	seed := designSeed("status/function/NewProgress#Bounded")
	useSeed(t, seed)
	propertyNewProgressBounded(t, seed)
}

// TestPropertyResolveStdinWins holds status/function/Resolve by property StdinWins.
func TestPropertyResolveStdinWins(t *testing.T) {
	seed := designSeed("status/function/Resolve#StdinWins")
	useSeed(t, seed)
	propertyResolveStdinWins(t, seed)
}

// TestPropertyResolveNeverInvents holds status/function/Resolve by property NeverInvents.
func TestPropertyResolveNeverInvents(t *testing.T) {
	seed := designSeed("status/function/Resolve#NeverInvents")
	useSeed(t, seed)
	propertyResolveNeverInvents(t, seed)
}
