// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

// Package quota — The context window and the account's rate limits. Pure;
// time is an argument.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package quota

import (
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 1, 1, 255), "NOT_IMPLEMENTED", "not implemented yet", "quota: a hand-written body is still a skeleton")

const (
	// KindContext is the context window of the conversation.
	KindContext Kind = "context"
	// KindExtra is the monthly extra-usage credit balance.
	KindExtra Kind = "extra"
	// KindScoped is a 7-day quota restricted to one model family.
	KindScoped Kind = "weekly_scoped"
	// KindSession is the rolling 5-hour quota.
	KindSession Kind = "session"
	// KindWeekly is the rolling 7-day quota, all models.
	KindWeekly Kind = "weekly"
	// LevelCritical is a constant of the design.
	LevelCritical Level = 3
	// LevelHigh is a constant of the design.
	LevelHigh Level = 2
	// LevelLow is a constant of the design.
	LevelLow Level = 0
	// LevelMedium is a constant of the design.
	LevelMedium Level = 1
	// SessionWindow is the rolling 5-hour rate limit window.
	SessionWindow time.Duration = 5 * time.Hour
	// SourceAPI is the OAuth usage endpoint.
	SourceAPI Source = "api"
	// SourceNone marks an absent limit.
	SourceNone Source = ""
	// SourceStdin is the payload the host pipes on every redraw.
	SourceStdin Source = "stdin"
	// WeeklyWindow is the rolling 7-day rate limit window.
	WeeklyWindow time.Duration = 7 * 24 * time.Hour
)

// Extra — The monthly extra-usage credit balance, in minor units.
type Extra struct {
	Enabled    bool   `json:"enabled,omitempty"`
	Percent    int    `json:"percent,omitempty"`
	UsedMinor  int    `json:"used_minor,omitempty"`
	LimitMinor int    `json:"limit_minor,omitempty"`
	Currency   string `json:"currency,omitempty"`
	Exponent   int    `json:"exponent,omitempty"`
	Source     Source `json:"source,omitempty"`
}

// IsValid is a method of the design.
func (ex Extra) IsValid() bool {
	return ex.isValid()
}

// Kind identifies which quota a Limit measures; plans expose different
// subsets.
type Kind string

// Level is the severity of a consumption.
type Level int

// Limit — One quota and its refill schedule. A zero Limit means the plan
// does not expose it — never 0 %.
type Limit struct {
	Kind     Kind          `json:"kind,omitempty"`
	Label    string        `json:"label,omitempty"`
	Percent  int           `json:"percent,omitempty"`
	ResetsAt time.Time     `json:"resets_at,omitzero"`
	Window   time.Duration `json:"window,omitempty"`
	Active   bool          `json:"active,omitempty"`
	Source   Source        `json:"source,omitempty"`
}

// CursorPosition is a method of the design.
func (l Limit) CursorPosition(now time.Time) int {
	return l.cursorPosition(now)
}

// Elapsed is a method of the design.
func (l Limit) Elapsed(now time.Time) float64 {
	return l.elapsed(now)
}

// ExhaustsIn is a method of the design.
func (l Limit) ExhaustsIn(now time.Time) (time.Duration, bool) {
	return l.exhaustsIn(now)
}

// HasWindow is a method of the design.
func (l Limit) HasWindow() bool {
	return l.hasWindow()
}

// IsOnTrack is a method of the design.
func (l Limit) IsOnTrack(now time.Time) bool {
	return l.isOnTrack(now)
}

// IsValid is a method of the design.
func (l Limit) IsValid() bool {
	return l.isValid()
}

// Pace is a method of the design.
func (l Limit) Pace(now time.Time) int {
	return l.pace(now)
}

// Progress is a method of the design.
func (l Limit) Progress() Progress {
	return l.progress()
}

// Projected is a method of the design.
func (l Limit) Projected(now time.Time) int {
	return l.projected(now)
}

// Remaining is a method of the design.
func (l Limit) Remaining(now time.Time) time.Duration {
	return l.remaining(now)
}

// Progress — A consumption percentage.
type Progress struct {
	Percent int `json:"percent"`
}

// Level is a method of the design.
func (p Progress) Level() Level {
	return p.level()
}

// Set — Every quota that applies to the session; any field but Context may
// be absent.
type Set struct {
	Context Limit   `json:"context"`
	Session Limit   `json:"session"`
	Weekly  Limit   `json:"weekly"`
	Scoped  []Limit `json:"scoped,omitempty"`
	Extra   Extra   `json:"extra"`
}

// HasTimed is a method of the design.
func (s Set) HasTimed() bool {
	return s.hasTimed()
}

// ScopedFor is a method of the design.
func (s Set) ScopedFor(modelName string) []Limit {
	return s.scopedFor(modelName)
}

// Timed is a method of the design.
func (s Set) Timed() []Limit {
	return s.timed()
}

// Source records where a Limit was read from: stdin is authoritative and free,
// the API costs a request.
type Source string

// Timestamp — An instant written as a Unix epoch in seconds or as an RFC
// 3339 string; anything else is the zero instant, never an error.
type Timestamp struct {
	time.Time
}

// NewLimit builds a Limit with its percentage clamped to 0–100.
func NewLimit(kind Kind, label string, percent int, resetsAt time.Time, window time.Duration, source Source) Limit {
	return newLimit(kind, label, percent, resetsAt, window, source)
}

// NewProgress is a function of the design.
func NewProgress(totalTokens int, contextSize int) Progress {
	return newProgress(totalTokens, contextSize)
}

// Resolve merges stdin's quotas with the API's — stdin wins, the API adds
// what stdin cannot know, an absent bucket stays absent.
func Resolve(stdin Set, api Set) Set {
	return resolve(stdin, api)
}
