// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package cli — The client role's entry — never a non-zero exit on a bad
// payload, since this process is the host's prompt line.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package cli

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/render/show"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 2, 4, 255), "NOT_IMPLEMENTED", "not implemented yet", "cli: a hand-written body is still a skeleton")

// CLI is an adapter of the design.
type CLI struct {
	cli // its own state, hand-written
}

// NewCLI builds CLI: its body is the hand-written newCLI.
func NewCLI(showStatusLine show.ShowStatusLine, daemonStatus show.DaemonStatus, stopDaemon show.StopDaemon) *CLI {
	return newCLI(showStatusLine, daemonStatus, stopDaemon)
}

// Run is render/port/Command@v1's.
func (a *CLI) Run(ctx context.Context, args []string) error {
	return a.run(ctx, args)
}

var _ show.CommandV1 = (*CLI)(nil)
