// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:2fe8d86cbae61dd09910f21ff1088719bef537ae1defa6374bdd41ff060206d8

// Package cli — The client role's command, the default and fail-safe one:
// this process is the host's prompt line, it never fails and never writes a
// word of its own on stderr.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package cli

import (
	"context"

	"github.com/kitsunium/sdk/framework/kit"
	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/render/show"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 2, 4, 255), "NOT_IMPLEMENTED", "not implemented yet", "cli: a hand-written body is still a skeleton")

// Service is cli's framework service: what it declares, drawn and run.
var Service = kit.NewService("cli", "The client role's command, the default and fail-safe one: this process is the host's prompt line, it never fails and never writes a word of its own on stderr.")

var _ = Service.CLI("line", "prints the two lines of the status line", Line, kit.DefaultCommand(), kit.FailSafe())

// Line runs "line": its body is the hand-written line.
func Line(ctx context.Context, args []string, std kit.Stdio) int {
	return line(ctx, args, std)
}

// wired is what the handlers' twins reach, set by the role that mounts
// the component (Wire).
var wired struct {
	showStatusLine show.ShowStatusLine
	version        string
}

// Wire gives the handlers what they use: the role that mounts cli calls it
// before its App runs.
func Wire(showStatusLine show.ShowStatusLine, version string) {
	wired.showStatusLine = showStatusLine
	wired.version = version
}
