// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

// Package releases — The SDK's signed self-update: vendor keys, signature
// domain, automatic consent, no elevation, <bin>.prev with a probe and a
// rollback.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package releases

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/collect/state"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 15, 255), "NOT_IMPLEMENTED", "not implemented yet", "releases: a hand-written body is still a skeleton")

// Releases is an adapter of the design.
type Releases struct {
	releases // its own state, hand-written
}

// NewReleases builds Releases: its body is the hand-written newReleases.
func NewReleases(version string, vendorKey string) *Releases {
	return newReleases(version, vendorKey)
}

// Install is collect/port/ReleaseSource@v1's.
func (a *Releases) Install(ctx context.Context, rel state.Release) error {
	return a.install(ctx, rel)
}

// Latest is collect/port/ReleaseSource@v1's.
func (a *Releases) Latest(ctx context.Context) (state.Release, error) {
	return a.latest(ctx)
}

var _ collector.ReleaseSourceV1 = (*Releases)(nil)
