// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package releases — The SDK's signed self-update, with <bin>.prev kept, a
// probe and a rollback.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package releases

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/collect/state"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 15, 255), "NOT_IMPLEMENTED", "not implemented yet", "releases: a hand-written body is still a skeleton")

// Releases is an adapter of the design.
type Releases struct {
	releases // its own state, hand-written
}

// NewReleases builds Releases: its body is the hand-written newReleases.
func NewReleases() *Releases {
	return newReleases()
}

// Install is collect/port/ReleaseSource@v1's.
func (a *Releases) Install(ctx context.Context, rel state.Release) error {
	return a.install(ctx, rel)
}

// Latest is collect/port/ReleaseSource@v1's.
func (a *Releases) Latest(ctx context.Context) (state.Release, error) {
	return a.latest(ctx)
}

// Probe is collect/port/ReleaseSource@v1's.
func (a *Releases) Probe(ctx context.Context) error {
	return a.probe(ctx)
}

// Rollback is collect/port/ReleaseSource@v1's.
func (a *Releases) Rollback(ctx context.Context) error {
	return a.rollback(ctx)
}

var _ collector.ReleaseSourceV1 = (*Releases)(nil)
