// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:2fe8d86cbae61dd09910f21ff1088719bef537ae1defa6374bdd41ff060206d8

// Package client — What the host runs on every redraw.
package client

import (
	"context"

	"github.com/kitsunium/sdk/framework/kit"
	"github.com/kitsunium/sdk/framework/model"
	"github.com/kitsunium/statusline/render/cli"
	"github.com/kitsunium/statusline/render/daemonlink"
	"github.com/kitsunium/statusline/render/show"
	"github.com/kitsunium/statusline/render/systemclock"
)

// App is role client: the framework App of cli, profile cli.
var App = kit.NewApp("client", cli.Service).With(kit.Profile(model.ProfileCLI))

// Build is what the binary's build says: its variables, set by -ldflags -X.
type Build struct {
	Version   string
	VendorKey string
}

// Wire builds what role client's handlers use, and gives it to them.
func Wire(ctx context.Context, build Build) {
	link := daemonlink.NewLink(build.Version)
	clock := systemclock.NewClock()
	showStatusLine := show.NewShowStatusLine(link, clock)
	cli.Wire(showStatusLine, build.Version)
}
