// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fd66b2b6a3694bc24ec48192c387084ddcee0ebf9262003e13519df5987eff47

// Package client — What the host runs on every redraw.
package client

import (
	"context"

	"github.com/kitsunium/statusline/render/cli"
	"github.com/kitsunium/statusline/render/daemonlink"
	"github.com/kitsunium/statusline/render/show"
	"github.com/kitsunium/statusline/render/systemclock"
)

// Build is what the binary's build says: its variables, set by -ldflags -X.
type Build struct {
	Version   string
	VendorKey string
}

// Run builds role client and runs render/adapter/CLI.
func Run(ctx context.Context, args []string, build Build) error {
	link := daemonlink.NewLink(build.Version)
	clock := systemclock.NewClock()
	showStatusLine := show.NewShowStatusLine(link, clock)
	cli := cli.NewCLI(showStatusLine, build.Version)
	return cli.Run(ctx, args)
}
