// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

// Package credentials is the adapter component credentials of domain collect.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package credentials

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 11, 255), "NOT_IMPLEMENTED", "not implemented yet", "credentials: a hand-written body is still a skeleton")

// Credentials is an adapter of the design.
type Credentials struct {
	credentials // its own state, hand-written
}

// NewCredentials builds Credentials: its body is the hand-written newCredentials.
func NewCredentials() *Credentials {
	return newCredentials()
}

// Token is collect/port/TokenStore@v1's.
func (a *Credentials) Token(ctx context.Context) (string, error) {
	return a.token(ctx)
}

var _ collector.TokenStoreV1 = (*Credentials)(nil)
