// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

// Package sysinfo is the adapter component sysinfo of domain collect.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package sysinfo

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 9, 255), "NOT_IMPLEMENTED", "not implemented yet", "sysinfo: a hand-written body is still a skeleton")

// System is an adapter of the design.
type System struct {
	system // its own state, hand-written
}

// NewSystem builds System: its body is the hand-written newSystem.
func NewSystem() *System {
	return newSystem()
}

// Info is collect/port/SystemInfo@v1's.
func (a *System) Info(ctx context.Context) (snapshot.System, error) {
	return a.info(ctx)
}

var _ collector.SystemInfoV1 = (*System)(nil)
