// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package sessioncache is the adapter component sessioncache of domain
// collect.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package sessioncache

import (
	"context"
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/ipc"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 14, 255), "NOT_IMPLEMENTED", "not implemented yet", "sessioncache: a hand-written body is still a skeleton")

// Cache is an adapter of the design.
type Cache struct {
	cache // its own state, hand-written
}

// NewCache builds Cache: its body is the hand-written newCache.
func NewCache() *Cache {
	return newCache()
}

// Evict is collect/port/SessionCache@v1's.
func (a *Cache) Evict(ctx context.Context, now time.Time) (int, error) {
	return a.evict(ctx, now)
}

// Get is collect/port/SessionCache@v1's.
func (a *Cache) Get(ctx context.Context, key ipc.Key, now time.Time) (snapshot.Snapshot, bool, error) {
	return a.get(ctx, key, now)
}

// LastRequest is collect/port/SessionCache@v1's.
func (a *Cache) LastRequest(ctx context.Context) (time.Time, error) {
	return a.lastRequest(ctx)
}

// Len is collect/port/SessionCache@v1's.
func (a *Cache) Len(ctx context.Context) (int, error) {
	return a.lenBody(ctx)
}

// Put is collect/port/SessionCache@v1's.
func (a *Cache) Put(ctx context.Context, key ipc.Key, snap snapshot.Snapshot, now time.Time) error {
	return a.put(ctx, key, snap, now)
}

// Touch is collect/port/SessionCache@v1's.
func (a *Cache) Touch(ctx context.Context, key ipc.Key, now time.Time) error {
	return a.touch(ctx, key, now)
}

var _ collector.SessionCacheV1 = (*Cache)(nil)
