// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

// Package statuspage is the adapter component statuspage of domain collect.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package statuspage

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 12, 255), "NOT_IMPLEMENTED", "not implemented yet", "statuspage: a hand-written body is still a skeleton")

// StatusPage is an adapter of the design.
type StatusPage struct {
	statusPage // its own state, hand-written
}

// NewStatusPage builds StatusPage: its body is the hand-written newStatusPage.
func NewStatusPage() *StatusPage {
	return newStatusPage()
}

// Fetch is collect/port/StatusPage@v1's.
func (a *StatusPage) Fetch(ctx context.Context) (snapshot.Health, error) {
	return a.fetch(ctx)
}

var _ collector.StatusPageV1 = (*StatusPage)(nil)
