// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

// Command statusline — The status line, and the daemon that collects for it.
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	clientrole "github.com/kitsunium/statusline/cmd/statusline/client"
	daemonrole "github.com/kitsunium/statusline/cmd/statusline/daemon"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	err := run(ctx, os.Args[1:])
	stop()
	if err != nil {
		fmt.Fprintln(os.Stderr, "statusline:", err)
		os.Exit(errs.ExitCodeOf(err))
	}
}

// run picks the process role: a command word, else the default role.
func run(ctx context.Context, args []string) error {
	if len(args) > 0 {
		switch args[0] {
		case "daemon":
			return daemonrole.Run(ctx, args[1:], daemonrole.Build{Version: version, VendorKey: vendorKey})
		}
	}
	return clientrole.Run(ctx, args, clientrole.Build{Version: version, VendorKey: vendorKey})
}

// The build's variables: go build -ldflags "-X main.<name>=<value>".
var (
	version   = "dev"
	vendorKey = ""
)
