// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Command statusline — The status line, and the daemon that collects for it.
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	clientrole "github.com/kitsunium/statusline/cmd/statusline/client"
	daemonrole "github.com/kitsunium/statusline/cmd/statusline/daemon"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	err := run(ctx, os.Args[1:])
	stop()
	if err != nil {
		fmt.Fprintln(os.Stderr, "statusline:", err)
		os.Exit(errs.ExitCodeOf(err))
	}
}

// run picks the process role: a command word, else the default role.
func run(ctx context.Context, args []string) error {
	if len(args) > 0 {
		switch args[0] {
		case "daemon":
			return daemonrole.Run(ctx, args[1:])
		}
	}
	return clientrole.Run(ctx, args)
}
