// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package mcpconfig — The MCP servers from the managed file, the host's
// command line, the local, project and user scopes and the enabled plugins.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package mcpconfig

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 5, 255), "NOT_IMPLEMENTED", "not implemented yet", "mcpconfig: a hand-written body is still a skeleton")

// Config is an adapter of the design.
type Config struct {
	config // its own state, hand-written
}

// NewConfig builds Config: its body is the hand-written newConfig.
func NewConfig() *Config {
	return newConfig()
}

// Servers is collect/port/MCPConfig@v1's.
func (a *Config) Servers(ctx context.Context, projectDir string, hostPID int) ([]snapshot.MCPServer, error) {
	return a.servers(ctx, projectDir, hostPID)
}

var _ collector.MCPConfigV1 = (*Config)(nil)
