// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package systemclock is the adapter component systemclock of domain render.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package systemclock

import (
	"context"
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/render/show"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 2, 6, 255), "NOT_IMPLEMENTED", "not implemented yet", "systemclock: a hand-written body is still a skeleton")

// Clock is an adapter of the design.
type Clock struct {
	clock // its own state, hand-written
}

// NewClock builds Clock: its body is the hand-written newClock.
func NewClock() *Clock {
	return newClock()
}

// Now is render/port/Clock@v1's.
func (a *Clock) Now(ctx context.Context) (time.Time, error) {
	return a.now(ctx)
}

var _ show.ClockV1 = (*Clock)(nil)
