// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package ipc

import (
	"hash/fnv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path))
	return h.Sum64()
}

// TestPropertyInstanceCachePathInsideCache holds status/Instance.CachePath by property InsideCache.
func TestPropertyInstanceCachePathInsideCache(t *testing.T) {
	propertyInstanceCachePathInsideCache(t, designSeed("status/Instance.CachePath#InsideCache"))
}

// TestPropertyKeyHashStable holds status/Key.Hash by property Stable.
func TestPropertyKeyHashStable(t *testing.T) {
	propertyKeyHashStable(t, designSeed("status/Key.Hash#Stable"))
}

// TestPropertyBuildVersionStable holds status/function/BuildVersion by property Stable.
func TestPropertyBuildVersionStable(t *testing.T) {
	propertyBuildVersionStable(t, designSeed("status/function/BuildVersion#Stable"))
}

// TestPropertyCompareVersionsOrder holds status/function/CompareVersions by property Order.
func TestPropertyCompareVersionsOrder(t *testing.T) {
	propertyCompareVersionsOrder(t, designSeed("status/function/CompareVersions#Order"))
}

// TestPropertyCompatibleMajorOne holds status/function/Compatible by property MajorOne.
func TestPropertyCompatibleMajorOne(t *testing.T) {
	propertyCompatibleMajorOne(t, designSeed("status/function/Compatible#MajorOne"))
}

// TestPropertyHereUnderRuntimeDir holds status/function/Here by property UnderRuntimeDir.
func TestPropertyHereUnderRuntimeDir(t *testing.T) {
	propertyHereUnderRuntimeDir(t, designSeed("status/function/Here#UnderRuntimeDir"))
}

// TestPropertyLocateDistinct holds status/function/Locate by property Distinct.
func TestPropertyLocateDistinct(t *testing.T) {
	propertyLocateDistinct(t, designSeed("status/function/Locate#Distinct"))
}

// TestPropertyReadFrameRoundtrip holds status/function/ReadFrame by property Roundtrip.
func TestPropertyReadFrameRoundtrip(t *testing.T) {
	propertyReadFrameRoundtrip(t, designSeed("status/function/ReadFrame#Roundtrip"))
}

// TestPropertyWriteFrameLengthPrefixed holds status/function/WriteFrame by property LengthPrefixed.
func TestPropertyWriteFrameLengthPrefixed(t *testing.T) {
	propertyWriteFrameLengthPrefixed(t, designSeed("status/function/WriteFrame#LengthPrefixed"))
}
