// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

// Package ipc — The contract between the client and the daemon
// (statusline.ipc/v1) — frames, handshake, instance paths.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package ipc

import (
	"io"
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 1, 3, 255), "NOT_IMPLEMENTED", "not implemented yet", "ipc: a hand-written body is still a skeleton")

var (
	// ErrFrameTooLarge is "a frame is 1 MiB at most".
	ErrFrameTooLarge = errs.New(errs.Pack(64, 1, 3, 1), "FRAME_TOO_LARGE", "a frame is 1 MiB at most", "status/error/ErrFrameTooLarge")
)

const (
	// MaxFrame bounds one frame, in bytes.
	MaxFrame int = 1048576
	// OpSnapshot is a constant of the design.
	OpSnapshot string = "snapshot"
	// OpStatus is a constant of the design.
	OpStatus string = "status"
	// OpStop is a constant of the design.
	OpStop string = "stop"
	// Protocol is a constant of the design.
	Protocol string = "statusline.ipc/v1"
)

// Hello is a value object of the design.
type Hello struct {
	Protocol string `json:"protocol"`
	Version  string `json:"version"`
	PID      int    `json:"pid"`
}

// Instance — Where one daemon instance lives; both roles derive the same
// paths.
type Instance struct {
	Dir       string
	Socket    string
	Lock      string
	Cache     string
	State     string
	Log       string
	PID       string
	Heartbeat string
}

// CachePath is a method of the design.
func (i Instance) CachePath(key Key) string {
	return i.cachePath(key)
}

// Key — What a session's state is kept by (D5) — session, transcript,
// directory — and the client's task list.
type Key struct {
	SessionID      string `json:"session_id,omitempty"`
	TranscriptPath string `json:"transcript_path,omitempty"`
	SessionDir     string `json:"session_dir,omitempty"`
	TaskListID     string `json:"task_list_id,omitempty"`
}

// Hash is a method of the design.
func (k Key) Hash() string {
	return k.hash()
}

// LocateInput is a value object of the design.
type LocateInput struct {
	RuntimeDir string
	UID        int
	ConfigDir  string
	Executable string
}

// Network is a value object of the design.
type Network struct {
	UsageFetchedAt  time.Time `json:"usage_fetched_at,omitzero"`
	UsageAttemptAt  time.Time `json:"usage_attempt_at,omitzero"`
	UsageRetryAfter time.Time `json:"usage_retry_after,omitzero"`
	UsageStatus     int       `json:"usage_status,omitempty"`
	HealthFetchedAt time.Time `json:"health_fetched_at,omitzero"`
	HealthAttemptAt time.Time `json:"health_attempt_at,omitzero"`
}

// Request is a value object of the design.
type Request struct {
	Op  string `json:"op"`
	Key Key    `json:"key"`
}

// Response is a value object of the design.
type Response struct {
	Snapshot *snapshot.Snapshot `json:"snapshot,omitempty"`
	Status   *Status            `json:"status,omitempty"`
	Error    string             `json:"error,omitempty"`
}

// Status is a value object of the design.
type Status struct {
	Version     string    `json:"version"`
	PID         int       `json:"pid"`
	Executable  string    `json:"executable"`
	StartedAt   time.Time `json:"started_at"`
	LastRequest time.Time `json:"last_request,omitzero"`
	Sessions    int       `json:"sessions"`
	Network     Network   `json:"network"`
	BadVersion  string    `json:"bad_version,omitempty"`
}

// CompareVersions is a function of the design.
func CompareVersions(a string, b string) int {
	return compareVersions(a, b)
}

// Compatible is a function of the design.
func Compatible(protocol string) bool {
	return compatible(protocol)
}

// Here locates the instance of the running executable from the environment.
func Here() (Instance, error) {
	return here()
}

// Locate is a function of the design.
func Locate(in LocateInput) Instance {
	return locate(in)
}

// ReadFrame is a function of the design.
func ReadFrame(r io.Reader, v any) error {
	return readFrame(r, v)
}

// WriteFrame is a function of the design.
func WriteFrame(w io.Writer, v any) error {
	return writeFrame(w, v)
}
