// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

// Package gitcli is the adapter component gitcli of domain collect.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package gitcli

import (
	"context"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/collect/collector"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 4, 255), "NOT_IMPLEMENTED", "not implemented yet", "gitcli: a hand-written body is still a skeleton")

// Git is an adapter of the design.
type Git struct {
	git // its own state, hand-written
}

// NewGit builds Git: its body is the hand-written newGit.
func NewGit() *Git {
	return newGit()
}

// DiffStats is collect/port/Repository@v1's.
func (a *Git) DiffStats(ctx context.Context, dir string) (snapshot.Changes, error) {
	return a.diffStats(ctx, dir)
}

// Status is collect/port/Repository@v1's.
func (a *Git) Status(ctx context.Context, dir string) (snapshot.GitStatus, error) {
	return a.status(ctx, dir)
}

var _ collector.RepositoryV1 = (*Git)(nil)
