// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:371eb9b52162ca35da1e8cae0f2f88f50639e87b018bcd6e1cd760b0ba42b78d

// Package state — The daemon's bookkeeping — the network with its 429
// back-off, the update with its bad version.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package state

import (
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/quota"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 3, 1, 255), "NOT_IMPLEMENTED", "not implemented yet", "state: a hand-written body is still a skeleton")

var (
	// ErrProbeFailed is "the new binary failed its probe and was rolled back".
	ErrProbeFailed = errs.New(errs.Pack(64, 3, 1, 2), "PROBE_FAILED", "the new binary failed its probe and was rolled back", "collect/error/ErrProbeFailed")
	// ErrUsageUnavailable is "the usage API is unavailable".
	ErrUsageUnavailable = errs.New(errs.Pack(64, 3, 1, 1), "USAGE_UNAVAILABLE", "the usage API is unavailable", "collect/error/ErrUsageUnavailable")
)

const (
	// EvictAfter is how long a key may go unrequested.
	EvictAfter time.Duration = 60 * time.Second
	// Freshness is how old a snapshot may be and still be served as is.
	Freshness time.Duration = 750 * time.Millisecond
	// HealthMaxAge is how old a summary may be and still be drawn.
	HealthMaxAge time.Duration = 15 * time.Minute
	// HealthTTL is how often the status page is asked at most.
	HealthTTL time.Duration = 2 * time.Minute
	// UpdateInterval is how often a release is looked for.
	UpdateInterval time.Duration = time.Hour
	// UsageTTL is how often the usage API is asked at most.
	UsageTTL time.Duration = 60 * time.Second
)

// HostSession is a value object of the design.
type HostSession struct {
	PID     int
	Working bool
}

// Network bookkeeping, persisted so that a restarted daemon keeps honouring a
// 429.
type Network struct {
	Usage           quota.Set       `json:"usage"`
	HasUsage        bool            `json:"has_usage,omitempty"`
	UsageFetchedAt  time.Time       `json:"usage_fetched_at,omitzero"`
	UsageAttemptAt  time.Time       `json:"usage_attempt_at,omitzero"`
	UsageRetryAfter time.Time       `json:"usage_retry_after,omitzero"`
	UsageFailures   int             `json:"usage_failures,omitempty"`
	UsageStatus     int             `json:"usage_status,omitempty"`
	Health          snapshot.Health `json:"health,omitempty"`
	HealthFetchedAt time.Time       `json:"health_fetched_at,omitzero"`
	HealthAttemptAt time.Time       `json:"health_attempt_at,omitzero"`
}

// CurrentHealth is a method of the design.
func (n Network) CurrentHealth(now time.Time) snapshot.Health {
	return n.currentHealth(now)
}

// HealthDue is a method of the design.
func (n Network) HealthDue(now time.Time) bool {
	return n.healthDue(now)
}

// RecordHealth is a method of the design.
func (n Network) RecordHealth(h snapshot.Health, now time.Time) Network {
	return n.recordHealth(h, now)
}

// RecordHealthFailure is a method of the design.
func (n Network) RecordHealthFailure(now time.Time) Network {
	return n.recordHealthFailure(now)
}

// RecordUsage is a method of the design.
func (n Network) RecordUsage(set quota.Set, now time.Time) Network {
	return n.recordUsage(set, now)
}

// RecordUsageFailure is a method of the design.
func (n Network) RecordUsageFailure(status int, retryAfter time.Duration, now time.Time) Network {
	return n.recordUsageFailure(status, retryAfter, now)
}

// UsageDue is a method of the design.
func (n Network) UsageDue(now time.Time) bool {
	return n.usageDue(now)
}

// RateLimited — The usage API's HTTP 429; RetryAfter is the server's
// Retry-After, zero when it gave none. An error (Error is hand-written).
type RateLimited struct {
	RetryAfter time.Duration
}

// Release is a value object of the design.
type Release struct {
	Version string
	Asset   string
}

// Update is a value object of the design.
type Update struct {
	CheckedAt  time.Time `json:"checked_at,omitzero"`
	BadVersion string    `json:"bad_version,omitempty"`
	Failures   int       `json:"failures,omitempty"`
	Installed  string    `json:"installed,omitempty"`
}

// Due is a method of the design.
func (u Update) Due(now time.Time) bool {
	return u.due(now)
}
