// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47

package state

import (
	"flag"
	"hash/fnv"
	"os"
	"strconv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:fa7ffd4c65dd859a6fca354b22d544d2152b83a6e0e1d75813a862cdabfe6f47"

// designSeed is the seed of a property: the design's digest and its path —
// and KIT_SEED when kit test -seed sets it.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path + "|" + os.Getenv("KIT_SEED")))
	return h.Sum64()
}

// useSeed logs a property's seed and hands it to pgregory.net/rapid, whose
// only public way in is its -rapid.seed flag: rapid.Check then draws the same
// values in every run of the same design — and in kit test -seed's.
func useSeed(t *testing.T, seed uint64) {
	t.Helper()
	t.Logf("property seed %d (go test -rapid.seed=%d replays it)", seed, seed)
	if f := flag.Lookup("rapid.seed"); f != nil {
		_ = f.Value.Set(strconv.FormatUint(seed, 10))
	}
}

// TestPropertyNetworkCurrentHealthUnknownPastMaxAge holds collect/Network.CurrentHealth by property UnknownPastMaxAge.
func TestPropertyNetworkCurrentHealthUnknownPastMaxAge(t *testing.T) {
	seed := designSeed("collect/Network.CurrentHealth#UnknownPastMaxAge")
	useSeed(t, seed)
	propertyNetworkCurrentHealthUnknownPastMaxAge(t, seed)
}

// TestPropertyNetworkHealthDueTTL holds collect/Network.HealthDue by property TTL.
func TestPropertyNetworkHealthDueTTL(t *testing.T) {
	seed := designSeed("collect/Network.HealthDue#TTL")
	useSeed(t, seed)
	propertyNetworkHealthDueTTL(t, seed)
}

// TestPropertyNetworkRecordHealthFresh holds collect/Network.RecordHealth by property Fresh.
func TestPropertyNetworkRecordHealthFresh(t *testing.T) {
	seed := designSeed("collect/Network.RecordHealth#Fresh")
	useSeed(t, seed)
	propertyNetworkRecordHealthFresh(t, seed)
}

// TestPropertyNetworkRecordHealthFailureKeepsLevel holds collect/Network.RecordHealthFailure by property KeepsLevel.
func TestPropertyNetworkRecordHealthFailureKeepsLevel(t *testing.T) {
	seed := designSeed("collect/Network.RecordHealthFailure#KeepsLevel")
	useSeed(t, seed)
	propertyNetworkRecordHealthFailureKeepsLevel(t, seed)
}

// TestPropertyNetworkRecordUsageResetsBackoff holds collect/Network.RecordUsage by property ResetsBackoff.
func TestPropertyNetworkRecordUsageResetsBackoff(t *testing.T) {
	seed := designSeed("collect/Network.RecordUsage#ResetsBackoff")
	useSeed(t, seed)
	propertyNetworkRecordUsageResetsBackoff(t, seed)
}

// TestPropertyNetworkRecordUsageFailureBackoffBounded holds collect/Network.RecordUsageFailure by property BackoffBounded.
func TestPropertyNetworkRecordUsageFailureBackoffBounded(t *testing.T) {
	seed := designSeed("collect/Network.RecordUsageFailure#BackoffBounded")
	useSeed(t, seed)
	propertyNetworkRecordUsageFailureBackoffBounded(t, seed)
}

// TestPropertyNetworkUsageDueNeverBeforeRetryAfter holds collect/Network.UsageDue by property NeverBeforeRetryAfter.
func TestPropertyNetworkUsageDueNeverBeforeRetryAfter(t *testing.T) {
	seed := designSeed("collect/Network.UsageDue#NeverBeforeRetryAfter")
	useSeed(t, seed)
	propertyNetworkUsageDueNeverBeforeRetryAfter(t, seed)
}

// TestPropertyUpdateDueHourly holds collect/Update.Due by property Hourly.
func TestPropertyUpdateDueHourly(t *testing.T) {
	seed := designSeed("collect/Update.Due#Hourly")
	useSeed(t, seed)
	propertyUpdateDueHourly(t, seed)
}
