// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package state

import (
	"hash/fnv"
	"testing"
)

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path))
	return h.Sum64()
}

// TestPropertyNetworkCurrentHealthUnknownPastMaxAge holds collect/Network.CurrentHealth by property UnknownPastMaxAge.
func TestPropertyNetworkCurrentHealthUnknownPastMaxAge(t *testing.T) {
	propertyNetworkCurrentHealthUnknownPastMaxAge(t, designSeed("collect/Network.CurrentHealth#UnknownPastMaxAge"))
}

// TestPropertyNetworkHealthDueTTL holds collect/Network.HealthDue by property TTL.
func TestPropertyNetworkHealthDueTTL(t *testing.T) {
	propertyNetworkHealthDueTTL(t, designSeed("collect/Network.HealthDue#TTL"))
}

// TestPropertyNetworkRecordHealthFresh holds collect/Network.RecordHealth by property Fresh.
func TestPropertyNetworkRecordHealthFresh(t *testing.T) {
	propertyNetworkRecordHealthFresh(t, designSeed("collect/Network.RecordHealth#Fresh"))
}

// TestPropertyNetworkRecordHealthFailureKeepsLevel holds collect/Network.RecordHealthFailure by property KeepsLevel.
func TestPropertyNetworkRecordHealthFailureKeepsLevel(t *testing.T) {
	propertyNetworkRecordHealthFailureKeepsLevel(t, designSeed("collect/Network.RecordHealthFailure#KeepsLevel"))
}

// TestPropertyNetworkRecordUsageResetsBackoff holds collect/Network.RecordUsage by property ResetsBackoff.
func TestPropertyNetworkRecordUsageResetsBackoff(t *testing.T) {
	propertyNetworkRecordUsageResetsBackoff(t, designSeed("collect/Network.RecordUsage#ResetsBackoff"))
}

// TestPropertyNetworkRecordUsageFailureBackoffBounded holds collect/Network.RecordUsageFailure by property BackoffBounded.
func TestPropertyNetworkRecordUsageFailureBackoffBounded(t *testing.T) {
	propertyNetworkRecordUsageFailureBackoffBounded(t, designSeed("collect/Network.RecordUsageFailure#BackoffBounded"))
}

// TestPropertyNetworkUsageDueNeverBeforeRetryAfter holds collect/Network.UsageDue by property NeverBeforeRetryAfter.
func TestPropertyNetworkUsageDueNeverBeforeRetryAfter(t *testing.T) {
	propertyNetworkUsageDueNeverBeforeRetryAfter(t, designSeed("collect/Network.UsageDue#NeverBeforeRetryAfter"))
}

// TestPropertyUpdateDueHourly holds collect/Update.Due by property Hourly.
func TestPropertyUpdateDueHourly(t *testing.T) {
	propertyUpdateDueHourly(t, designSeed("collect/Update.Due#Hourly"))
}
