// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

// Package show — One redraw, and the user's commands about the daemon.
//
// Its structure is generated from design/ (ADR 0010); its bodies are the
// hand-written twins beside this file.
package show

import (
	"context"
	"time"

	"github.com/kitsunium/sdk/pkg/v1/errs"
	"github.com/kitsunium/statusline/ipc"
	"github.com/kitsunium/statusline/snapshot"
)

// errNotImplemented is what a skeleton answers until its body is written:
// kit check reads a twin that returns it as a stub.
var errNotImplemented = errs.New(errs.Pack(64, 2, 3, 255), "NOT_IMPLEMENTED", "not implemented yet", "show: a hand-written body is still a skeleton")

const (
	// OriginCache is a constant of the design.
	OriginCache string = "cache"
	// OriginDaemon is a constant of the design.
	OriginDaemon string = "daemon"
	// OriginNone is a constant of the design.
	OriginNone string = "none"
)

// ClockV1 is an outbound port: the product calls through it.
type ClockV1 interface {
	Now(ctx context.Context) (time.Time, error)
}

// CommandV1 is the client role's entry.
type CommandV1 interface {
	Run(ctx context.Context, args []string) error
}

// DaemonControlV1 is an outbound port: the product calls through it.
type DaemonControlV1 interface {
	Status(ctx context.Context) (ipc.Status, error)
	Stop(ctx context.Context) error
}

// SnapshotSourceV1 gives a session's snapshot and where it came from
// (Origin*).
type SnapshotSourceV1 interface {
	Snapshot(ctx context.Context, key ipc.Key) (snapshot.Snapshot, string, error)
}

// DaemonStatus is a use case of the design.
type DaemonStatus interface {
	Execute(ctx context.Context, in DaemonStatusInput) (DaemonStatusOutput, error)
}

// DaemonStatusInput is DaemonStatus's input: a field added breaks no caller.
type DaemonStatusInput struct {
}

// DaemonStatusOutput is DaemonStatus's output.
type DaemonStatusOutput struct {
	Running bool
	Status  ipc.Status
}

// DaemonStatusHandler runs DaemonStatus: its body is the hand-written execute.
type DaemonStatusHandler struct {
	daemonControl DaemonControlV1
}

// NewDaemonStatus builds DaemonStatus on what it calls.
func NewDaemonStatus(daemonControl DaemonControlV1) *DaemonStatusHandler {
	return &DaemonStatusHandler{daemonControl: daemonControl}
}

// Execute runs DaemonStatus.
func (h *DaemonStatusHandler) Execute(ctx context.Context, in DaemonStatusInput) (DaemonStatusOutput, error) {
	return h.execute(ctx, in)
}

var _ DaemonStatus = (*DaemonStatusHandler)(nil)

// ShowStatusLine — The host's payload keyed as the daemon keeps it, the
// snapshot drawn at the clock's instant, stdin's quotas winning.
type ShowStatusLine interface {
	Execute(ctx context.Context, in ShowStatusLineInput) (ShowStatusLineOutput, error)
}

// ShowStatusLineInput is ShowStatusLine's input: a field added breaks no caller.
type ShowStatusLineInput struct {
	Stdin []byte
	Env   map[string]string
}

// ShowStatusLineOutput is ShowStatusLine's output.
type ShowStatusLineOutput struct {
	Line   string
	Origin string
}

// ShowStatusLineHandler runs ShowStatusLine: its body is the hand-written execute.
type ShowStatusLineHandler struct {
	snapshotSource SnapshotSourceV1
	clock          ClockV1
}

// NewShowStatusLine builds ShowStatusLine on what it calls.
func NewShowStatusLine(snapshotSource SnapshotSourceV1, clock ClockV1) *ShowStatusLineHandler {
	return &ShowStatusLineHandler{snapshotSource: snapshotSource, clock: clock}
}

// Execute runs ShowStatusLine.
func (h *ShowStatusLineHandler) Execute(ctx context.Context, in ShowStatusLineInput) (ShowStatusLineOutput, error) {
	return h.execute(ctx, in)
}

var _ ShowStatusLine = (*ShowStatusLineHandler)(nil)

// StopDaemon is a use case of the design.
type StopDaemon interface {
	Execute(ctx context.Context, in StopDaemonInput) (StopDaemonOutput, error)
}

// StopDaemonInput is StopDaemon's input: a field added breaks no caller.
type StopDaemonInput struct {
}

// StopDaemonOutput is StopDaemon's output.
type StopDaemonOutput struct {
	WasRunning bool
}

// StopDaemonHandler runs StopDaemon: its body is the hand-written execute.
type StopDaemonHandler struct {
	daemonControl DaemonControlV1
}

// NewStopDaemon builds StopDaemon on what it calls.
func NewStopDaemon(daemonControl DaemonControlV1) *StopDaemonHandler {
	return &StopDaemonHandler{daemonControl: daemonControl}
}

// Execute runs StopDaemon.
func (h *StopDaemonHandler) Execute(ctx context.Context, in StopDaemonInput) (StopDaemonOutput, error) {
	return h.execute(ctx, in)
}

var _ StopDaemon = (*StopDaemonHandler)(nil)
