// Code generated by kit from design/v1; DO NOT EDIT.
// kit:digest sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3

package show

import (
	"context"
	"hash/fnv"
	"slices"
	"testing"
	"time"

	"github.com/kitsunium/statusline/ipc"
	"github.com/kitsunium/statusline/snapshot"
)

// TestDaemonStatusReportsARunningDaemon is DaemonStatus's scenario "reports a running daemon" (success).
func TestDaemonStatusReportsARunningDaemon(t *testing.T) {
	uc, in, then := givenDaemonStatusReportsARunningDaemon(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("DaemonStatus: %v, want a success", err)
	}
	then(t, out)
}

// TestDaemonStatusReportsNoDaemon is DaemonStatus's scenario "reports no daemon" (success).
func TestDaemonStatusReportsNoDaemon(t *testing.T) {
	uc, in, then := givenDaemonStatusReportsNoDaemon(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("DaemonStatus: %v, want a success", err)
	}
	then(t, out)
}

// TestShowStatusLineDrawsTheDaemonsSnapshotWithStdinWinning is ShowStatusLine's scenario "draws the daemons snapshot with stdin winning" (success).
func TestShowStatusLineDrawsTheDaemonsSnapshotWithStdinWinning(t *testing.T) {
	uc, in, then := givenShowStatusLineDrawsTheDaemonsSnapshotWithStdinWinning(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("ShowStatusLine: %v, want a success", err)
	}
	then(t, out)
}

// TestShowStatusLineDrawsFromStdinAloneWhenNothingIsKnown is ShowStatusLine's scenario "draws from stdin alone when nothing is known" (success).
func TestShowStatusLineDrawsFromStdinAloneWhenNothingIsKnown(t *testing.T) {
	uc, in, then := givenShowStatusLineDrawsFromStdinAloneWhenNothingIsKnown(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("ShowStatusLine: %v, want a success", err)
	}
	then(t, out)
}

// TestStopDaemonStopsARunningDaemon is StopDaemon's scenario "stops a running daemon" (success).
func TestStopDaemonStopsARunningDaemon(t *testing.T) {
	uc, in, then := givenStopDaemonStopsARunningDaemon(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("StopDaemon: %v, want a success", err)
	}
	then(t, out)
}

// TestStopDaemonStopsNothingWithoutADaemon is StopDaemon's scenario "stops nothing without a daemon" (success).
func TestStopDaemonStopsNothingWithoutADaemon(t *testing.T) {
	uc, in, then := givenStopDaemonStopsNothingWithoutADaemon(t)
	out, err := uc.Execute(t.Context(), in)
	if err != nil {
		t.Fatalf("StopDaemon: %v, want a success", err)
	}
	then(t, out)
}

// designDigest is the design the properties run under: with the property's
// path, it seeds its values, so a pull request replays the same ones.
const designDigest = "sha256:d45b2928cba7e8198c9466409eef5b3a5f54361857217a2585461fb161fccbd3"

// designSeed is the seed of a property: the design's digest and its path.
func designSeed(path string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(designDigest + "|" + path))
	return h.Sum64()
}

// TestPropertyShowStatusLineTotal holds render/usecase/ShowStatusLine by property Total.
func TestPropertyShowStatusLineTotal(t *testing.T) {
	propertyShowStatusLineTotal(t, designSeed("render/usecase/ShowStatusLine#Total"))
}

// sequenceRecorder wraps the ports a sequence goes through, and records each
// call in order.
type sequenceRecorder struct {
	calls *[]string
}

// RecordShowClockV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordShowClockV1(next ClockV1) ClockV1 {
	return recordedshowClockV1{next: next, calls: r.calls}
}

type recordedshowClockV1 struct {
	next  ClockV1
	calls *[]string
}

func (x recordedshowClockV1) Now(ctx context.Context) (time.Time, error) {
	*x.calls = append(*x.calls, "render/port/Clock@v1.Now")
	return x.next.Now(ctx)
}

// RecordShowSnapshotSourceV1 records the calls to next, then makes them.
func (r sequenceRecorder) RecordShowSnapshotSourceV1(next SnapshotSourceV1) SnapshotSourceV1 {
	return recordedshowSnapshotSourceV1{next: next, calls: r.calls}
}

type recordedshowSnapshotSourceV1 struct {
	next  SnapshotSourceV1
	calls *[]string
}

func (x recordedshowSnapshotSourceV1) Snapshot(ctx context.Context, key ipc.Key) (snapshot.Snapshot, string, error) {
	*x.calls = append(*x.calls, "render/port/SnapshotSource@v1.Snapshot")
	return x.next.Snapshot(ctx, key)
}

// TestSequenceRenderWarm is the order of sequence render-warm: the diagram's links, in the
// diagram's order (D21).
func TestSequenceRenderWarm(t *testing.T) {
	var got []string
	run := givenSequenceRenderWarm(t, sequenceRecorder{calls: &got})
	if err := run(t.Context()); err != nil {
		t.Fatalf("the sequence failed: %v", err)
	}
	want := []string{"render/port/SnapshotSource@v1.Snapshot", "render/port/Clock@v1.Now"}
	if !slices.Equal(got, want) {
		t.Errorf("the calls: %q, want %q", got, want)
	}
}
